const taiwaneseDict = {
  "1": "tsi̍t",
  "2": "nńg",
  "3": "saⁿ",
  "123": "tsi̍t nn̄g saⁿ",
  "456": "sì gō͘ la̍k",
  "789": "tshit peh káu",
  "錄音": "lo̍k-im",
  "測試": "tshik-sì",
  "錄音測試": "lo̍k-im tshik-sì",
  "錄": "lo̍k",
  "音": "im",
  "測": "tshik",
  "試": "sì",
  "你好吗": "lí hó bô",
  "謝謝": "to-siā",
  "對不起": "tùi-bû-khí",
  "沒關係": "bô-kwan-hē",
  "再見": "chài-kiàn",
  "早安": "chá-bó͘",
  "晚安": "bān-an",
  "吃飯": "chia̍h-pn̄g",
  "吃早餐": "chia̍h-chá-chhan",
  "吃午餐": "chia̍h-tiong-chhan",
  "吃晚餐": "chia̍h-bān-chhan",
  "喝水": "lim-chúi",
  "喝茶": "lim-tê",
  "喝湯": "lim-thng",
  "吃藥": "chia̍h-io̍h",
  "餓": "tó͘-gō͘",
  "飽": "pá",
  "好吃": "hó-chia̍h",
  "不好吃": "bōe-hó-chia̍h",
  "熱": "sio",
  "冷": "kínn",
  "睡覺": "khùn-khì",
  "起床": "khí-chhn̂g",
  "洗澡": "sé-tsa̍k",
  "洗手": "sé-chhiú",
  "洗臉": "sé-bīn",
  "刷牙": "chhòe-khí",
  "擦身體": "chhit-sin-khu",
  "換衣服": "uā-saⁿ-khò͘",
  "穿衣服": "chhēng-saⁿ-khò͘",
  "脫衣服": "thng-saⁿ-khò͘",
  "洗頭": "sé-thâu",
  "擦藥": "chhit-io̍h",
  "量體溫": "niû-thé-un",
  "量血壓": "niû-hiat-ap",
  "頭痛": "thâu-thiànn",
  "肚子痛": "tó͘-thiànn",
  "手痛": "chhiú-thiànn",
  "腳痛": "kha-thiànn",
  "背痛": "pūi-thiànn",
  "感冒": "kám-bō",
  "發燒": "hoat-sio",
  "咳嗽": "kheh-sàu",
  "喉嚨痛": "âu-lêng-thiànn",
  "流鼻水": "lâu-phīⁿ-chúi",
  "拉肚子": "lā-tó͘",
  "便秘": "piān-pì",
  "有沒有痛": "ū bô thiànn",
  "哪裡痛": "tó-ūi thiànn",
  "舒服": "khòai-ho̍k",
  "不舒服": "bōe-khòai-ho̍k",
  "累": "lē",
  "想睡": "siūⁿ khùn-khì",
  "睡不著": "khùn bōe-tio̍h",
  "開心": "khai-sim",
  "難過": "lân-kóe",
  "害怕": "khioh-hiā",
  "生氣": "seng-khì",
  "冷靜": "léng-chēng",
  "笑": "chhiò",
  "哭": "khàu",
  "幫忙": "pang-bâng",
  "請問": "chhiáⁿ-mn̄g",
  "可以": "khó-í",
  "不可以": "bōe-khó-i",
  "好": "hó",
  "不好": "bōe-hó",
  "慢慢": "bān-bān",
  "小心": "sió-sim",
  "等一下": "tán-chi̍t-ē",
  "趕快": "kín-khoài",
  "輪椅": "lûn-í",
  "助行器": "tsō-hîng-khì",
  "拐杖": "kuá-tsiùnn",
  "翻身": "huan-sin",
  "坐起來": "chē-khí-lâi",
  "躺下來": "thn̄g-lo̍h-khì",
  "走路": "kiâⁿ-lō͘",
  "站起來": "khí-khí-lâi",
  "坐下": "chē-lo̍h",
  "拿": "khioh",
  "放": "pàng",
  "換尿布": "uā-jiō-pòo",
  "洗屁屁": "sé-phī-phī",
  "擦屁屁": "chhit-phī-phī",
  "上廁所": "chhiong-chhek-só͘",
  "大便": "tōa-piàn",
  "小便": "sió-piàn",
  "失禁": "sit-kìm",
  "床單": "chhn̂g-toaⁿ",
  "棉被": "mî-phōe",
  "枕頭": "chím-thâu",
  "毛巾": "mô͘-kin",
  "衛生紙": "ūi-seng-chóa",
  "肥皂": "pûi-chô",
  "牙膏": "khí-kô",
  "牙刷": "khí-so",
  "水杯": "chúi-poe",
  "馬桶": "má-thóng",
  "擦屎": "chhit-sái",
  "擦尿": "chhit-jiō",
  "乾淨": "kan-cheng",
  "髒": "ang-chang",
  "擦汗": "chhit-khòaⁿ",
  "擦嘴": "chhit-chhùi",
  "剪指甲": "chhiat-chí-kah",
  "梳頭": "sê-thâu",
  "熱水": "sio-chúi",
  "冷水": "kóng-chúi",
  "開燈": "khai-teng",
  "關燈": "koan-teng",
  "開窗": "khai-thang",
  "關窗": "koan-thang",
  "開冷氣": "khai-léng-khì",
  "關冷氣": "koan-léng-khì",
  "拿藥": "khioh-io̍h",
  "吃藥了": "chia̍h-io̍h liáu",
  "藥水": "io̍h-chúi",
  "藥丸": "io̍h-oân",
  "藥膏": "io̍h-kô",
  "貼藥布": "thiap-io̍h-pò͘",
  "擦藥膏": "chhit-io̍h-kô",
  "有屎": "ū sái",
  "有尿": "ū jiō",
  "屎很多": "sái chē",
  "尿很多": "jiō chē",
  "屎臭": "sái chhàu",
  "尿臭": "jiō chhàu",
  "想屎": "siūⁿ sái",
  "想尿": "siūⁿ jiō",
  "屎不出": "sái bōe-chhut",
  "尿不出": "jiō bōe-chhut",
  "痛": "thiànn",
  "很痛": "kín thiànn",
  "痛這裡": "thiànn chia",
  "痛那裡": "thiànn hia",
  "頭暈": "thâu-tàng",
  "想吐": "siūⁿ thò͘",
  "吐了": "thò͘ liáu",
  "流汗": "lâu-khòaⁿ",
  "發抖": "hoat-chún",
  "怕冷": "phà kóng",
  "怕熱": "phà sio",
  "氣喘": "khì-chhoán",
  "鼻塞": "phīⁿ-sai",
  "流鼻涕": "lâu-phīⁿ-thí",
  "打噴嚏": "phah-phīn-thi",
  "癢": "chhiū",
  "很癢": "kín chhiū",
  "癢這裡": "chhiū chia",
  "癢那裡": "chhiū hia",
  "紅": "âng",
  "腫": "chhóng",
  "破皮": "phò-puê",
  "流血": "lâu-hiat",
  "擦傷": "chhit-siong",
  "瘀青": "ú-chheⁿ",
  "壓瘡": "ap-soan",
  "傷口": "siong-kháu",
  "貼OK繃": "thiap OK-pàng",
  "換藥": "uā-io̍h",
  "要休息": "ài hiū-khek",
  "要走": "ài kiâⁿ",
  "要坐": "ài chē",
  "要躺": "ài thn̄g",
  "扶我": "pû góa",
  "抱我": "phō góa",
  "推我": "thui góa",
  "拉我": "lā góa",
  "幫我起來": "pang góa khí-lâi",
  "幫我坐下": "pang góa chē-lo̍h",
  "幫我躺下": "pang góa thn̄g-lo̍h",
  "慢一點": "bān-chi̍t-ē",
  "快一點": "kín-chi̍t-ē",
  "輕一點": "kheng-chi̍t-ē",
  "重一點": "tāng-chi̍t-ē",
  "按這裡": "àn chia",
  "按那裡": "àn hia",
  "按摩": "àn-bô͘",
  "拍背": "phah-pūi",
  "拍手": "phah-chhiú",
  "拍腳": "phah-kha",
  "拍屁股": "phah-phī-kha",
  "熱敷": "sio-hù",
  "冷敷": "kóng-hù",
  "冰敷": "peng-hù",
  "拿冰": "khioh-peng",
  "拿熱水袋": "khioh-sio-chúi-tē",
  "拿毛毯": "khioh-mô͘-thán",
  "蓋被子": "kòa-phōe",
  "開電視": "khai-tiān-sī",
  "關電視": "koan-tiān-sī",
  "看電視": "khòaⁿ-tiān-sī",
  "換台": "uā-tâi",
  "大聲": "tōa-siaⁿ",
  "小聲": "sió-siaⁿ",
  "聽音樂": "thiaⁿ-im-ga̍k",
  "開音樂": "khai-im-ga̍k",
  "關音樂": "koan-im-ga̍k",
  "唱歌": "chhiò-kua",
  "聊天": "liâu-thiân",
  "講話": "kóng-ōe",
  "聽到": "thiaⁿ-tio̍h",
  "聽不到": "thiaⁿ-bōe-tio̍h",
  "看得到": "khòaⁿ-tio̍h",
  "看不到": "khòaⁿ-bōe-tio̍h",
  "眼睛花": "ba̍k-chiu-hoe",
  "耳鳴": "hīⁿ-bêng",
  "耳聾": "hīⁿ-lâng",
  "眼淚": "ba̍k-sái",
  "流淚": "lâu-ba̍k-sái",
  "鼻涕": "phīⁿ-thí",
  "擦鼻涕": "chhit-phīⁿ-thí",
  "打呼": "phah-khò͘",
  "睡著": "khùn-tio̍h",
  "醒了": "chhíⁿ liáu",
  "做夢": "chò-bōng",
  "惡夢": "pháinn-bōng",
  "叫我": "kiò góa",
  "叫醒": "kiò-chhíⁿ",
  "吵": "chhau",
  "安靜": "an-chēng",
  "好吵": "hó-chhau",
  "太吵": "thài-chhau",
  "很冷": "kín kóng",
  "很熱": "kín sio",
  "出汗": "chhut-khòaⁿ",
  "怕": "phà",
  "盆": "phún",
  "不怕": "bōe-phà",
  "緊張": "kín-chiong",
  "放鬆": "pàng-khuan",
  "笑笑": "chhiò-chhiò",
  "別哭": "bián khàu",
  "摸摸": "bong-bong",
  "抱抱": "phō-phō",
  "握手": "ak-chhiú",
  "拍肩": "phah-keng",
  "牽手": "khan-chhiú",
  "好摸": "hó-bong",
  "不好摸": "bōe-hó-bong",
  "軟": "nńg",
  "硬": "ngē",
  "滑": "ku̍t",
  "粗": "chho",
  "拿水": "khioh-chúi",
  "喝一口": "lim-chi̍t-kháu",
  "喝慢點": "lim bān-chi̍t-ē",
  "別嗆到": "bián chhèng-tio̍h",
  "嗆到": "chhèng-tio̍h",
  "吞下去": "thun-lo̍h-khì",
  "吐出來": "thò͘-chhut-lâi",
  "吃一口": "chia̍h-chi̍t-kháu",
  "吃慢點": "chia̍h bān-chi̍t-ē",
  "嚼": "chiah",
  "吞": "thun",
  "咬": "kā",
  "吐掉": "thò͘-tiāu",
  "硬吞": "ngē-thun",
  "吃不下": "chia̍h-bōe-lo̍h",
  "噎到": "iat-tio̍h",
  "多吃": "kīn chia̍h",
  "少吃": "chió chia̍h",
  "甜": "tiⁿ",
  "不甜": "bōe-tiⁿ",
  "鹹": "kiâm",
  "不鹹": "bōe-kiâm",
  "淡": "tām",
  "濃": "lông",
  "軟飯": "nńg-pn̄g",
  "硬飯": "ngē-pn̄g",
  "稀飯": "hê-pn̄g",
  "麵": "mī",
  "湯麵": "thng-mī",
  "炒麵": "chhá-mī",
  "湯": "thng",
  "菜": "chhài",
  "肉": "bah",
  "魚": "hî",
  "雞": "koe",
  "蛋": "nn̄g",
  "豆腐": "tāu-hū",
  "水果": "chhài-kó",
  "蘋果": "phōng-kó",
  "香蕉": "chhio-kio",
  "橘子": "kiat",
  "葡萄": "phû-tô",
  "西瓜": "si-kua",
  "切水果": "chhiat-chhài-kó",
  "剝皮": "pak-phuê",
  "去籽": "khì-chí",
  "洗水果": "sé-chhài-kó",
  "牛奶": "gû-lin",
  "豆漿": "tāu-chiuⁿ",
  "果汁": "kó-chiap",
  "咖啡": "ka-pi",
  "茶": "tê",
  "冰": "peng",
  "加冰": "ka-peng",
  "不加冰": "bōe-ka-peng",
  "熱飲": "sio-im",
  "冷飲": "kóng-im",
  "吸管": "khip-kóng",
  "用吸管": "iōng khip-kóng",
  "不要吸管": "mài khip-kóng",
  "碗": "óaⁿ",
  "盤子": "pôaⁿ",
  "筷子": "thî",
  "湯匙": "thng-kí",
  "叉子": "chhâ-á",
  "刀子": "to-á",
  "洗碗": "sé-óaⁿ",
  "擦碗": "chhit-óaⁿ",
  "洗菜": "sé-chhài",
  "切菜": "chhiat-chhài",
  "煮": "chú",
  "炒": "chhá",
  "蒸": "chheng",
  "烤": "khan",
  "燙": "thǹg",
  "冷掉": "kóng-tiāu",
  "熱一下": "sio-chi̍t-ē",
  "餵我": "chī góa",
  "一口一口": "chi̍t-kháu chi̍t-kháu",
  "慢慢餵": "bān-bān chī",
  "別弄掉": "bián lóng-tiāu",
  "弄掉了": "lóng-tiāu liáu",
  "擦掉": "chhit-tiāu",
  "弄髒": "lóng-ang-chang",
  "換桌布": "uā-toh-pò͘",
  "拿紙": "khioh-chóa",
  "擦桌": "chhit-toh",
  "地板髒": "tē-pán ang-chang",
  "掃地": "sàu-tē",
  "拖地": "thoa-tē",
  "垃圾": "la-sap",
  "丟垃圾": "tiāu la-sap",
  "垃圾桶": "la-sap-tháng",
  "垃圾袋": "la-sap-tē",
  "洗衣服": "sé-saⁿ-khò͘",
  "曬衣服": "sài-saⁿ-khò͘",
  "收衣服": "siu-saⁿ-khò͘",
  "折衣服": "chip-saⁿ-khò͘",
  "燙衣服": "thǹg-saⁿ-khò͘",
  "衣服髒": "saⁿ-khò͘ ang-chang",
  "換褲子": "uā-khò͘",
  "穿鞋": "chhēng-ôe",
  "脫鞋": "thng-ôe",
  "穿襪": "chhēng-bē",
  "脫襪": "thng-bē",
  "帽子": "bō-á",
  "戴帽子": "tì-bō-á",
  "拿帽子": "khioh-bō-á",
  "眼鏡": "gán-kiàⁿ",
  "戴眼鏡": "tì-gán-kiàⁿ",
  "拿眼鏡": "khioh-gán-kiàⁿ",
  "擦眼鏡": "chhit-gán-kiàⁿ",
  "眼鏡髒": "gán-kiàⁿ ang-chang",
  "手錶": "chhiú-piáu",
  "戴手錶": "tì-chhiú-piáu",
  "拿手錶": "khioh-chhiú-piáu",
  "時間": "sî-kan",
  "幾點": "kúi-tiám",
  "現在": "hiān-tsāi",
  "早上": "tsá-khí",
  "中午": "tiong-ngó͘",
  "晚上": "àm-sî",
  "半夜": "pòaⁿ-iā",
  "天亮": "thiⁿ-liàng",
  "天黑": "thiⁿ-o͘",
  "今天": "kin-á-ji̍t",
  "明天": "bîn-á-ji̍t",
  "昨天": "tsô-ji̍t",
  "星期一": "seng-kî-it",
  "星期二": "seng-kî-jī",
  "星期三": "seng-kî-sann",
  "星期四": "seng-kî-sì",
  "星期五": "seng-kî-gō͘",
  "星期六": "seng-kî-la̍k",
  "星期日": "seng-kî-ji̍t",
  "日期": "ji̍t-kî",
  "幾號": "kúi-hō",
  "天氣": "thinn-khì",
  "晴天": "chêng-thiⁿ",
  "下雨": "hō͘-lô͘",
  "雨傘": "hō͘-sòaⁿ",
  "雨衣": "hō͘-i",
  "風大": "hong tōa",
  "颱風": "thâi-hong",
  "雷": "lûi",
  "閃電": "sih-tiān",
  "彩虹": "chhái-hông",
  "太陽": "thài-iông",
  "月亮": "goe̍h-niû",
  "星星": "chhiⁿ-chhiⁿ",
  "雲": "hûn",
  "風": "hong",
  "春天": "chhun-thiⁿ",
  "夏天": "hē-thiⁿ",
  "秋天": "chhiu-thiⁿ",
  "冬天": "tang-thiⁿ",
  "冷天": "kóng-thiⁿ",
  "熱天": "sio-thiⁿ",
  "出去": "chhut-khì",
  "散步": "sàn-pō͘",
  "曬太陽": "sài-thài-iông",
  "吹風": "chhoe-hong",
  "回家": "hôe-ke",
  "出門": "chhut-mn̂g",
  "外面": "gōa-bīn",
  "裡面": "lāi-bīn",
  "門": "mn̂g",
  "窗": "thang",
  "房間": "pâng-keng",
  "客廳": "kheh-thiaⁿ",
  "廚房": "tû-pâng",
  "臥室": "gōa-pâng",
  "浴室": "io̍k-keng",
  "廁所": "chhek-só͘",
  "陽台": "iông-tâi",
  "花園": "hoe-hn̂g",
  "花": "hoe",
  "樹": "chhiū",
  "草": "chháu",
  "鳥": "chiáu",
  "狗": "káu",
  "貓": "bâi",
  "叫": "kiò",
  "跑": "cháu",
  "跳": "thiàu",
  "睡": "khùn",
  "吃": "chiah",
  "玩": "sńg",
  "摸": "bong",
  "餵": "chī",
  "狗屎": "káu-sái",
  "撿屎": "kéng-sái",
  "洗狗": "sé-káu",
  "洗貓": "sé-bâi",
  "散步去": "sàn-pō͘ khì",
  "公園": "kong-hn̂g",
  "路邊": "lō͘-pêng",
  "市場": "chhī-tiûⁿ",
  "超市": "chhiau-chhī",
  "買菜": "bé-chhài",
  "買肉": "bé-bah",
  "買魚": "bé-hî",
  "買水果": "bé-chhài-kó",
  "買藥": "bé-io̍h",
  "買東西": "bé-tōng-sai",
  "錢": "tsînn",
  "多少錢": "kúi-chōe-chîⁿ",
  "付錢": "hù-chîⁿ",
  "找錢": "chhōe-chîⁿ",
  "便宜": "piān-gī",
  "貴": "kùi",
  "折扣": "chiat-khò͘",
  "免費": "bián-hùi",
  "發票": "hoat-phiò",
  "袋子": "tē-á",
  "塑膠袋": "sò͘-kó-tē",
  "提袋": "the̍h-tē",
  "推車": "thui-chhia",
  "籃子": "nâ-á",
  "挑": "thiah",
  "選": "soán",
  "新鮮": "sin-sian",
  "不新鮮": "bōe-sin-sian",
  "壞掉": "pháiⁿ-tiāu",
  "放冰箱": "pàng-peng-siong",
  "冰箱": "peng-siong",
  "冷藏": "léng-chhàng",
  "冷凍": "léng-tàng",
  "拿出來": "chhú-chhut-lâi",
  "放進去": "pàng-ji̍p-khì",
  "開冰箱": "khai-peng-siong",
  "關冰箱": "koan-peng-siong",
  "冰箱臭": "peng-siong chhàu",
  "清冰箱": "chheng-peng-siong",
  "微波": "bî-pho",
  "小心燙": "sió-sim thǹg",
  "燙手": "thǹg-chhiú",
  "燙嘴": "thǹg-chhùi",
  "吹涼": "chhoe-liâng",
  "放涼": "pàng-liâng",
  "放桌": "pàng-toh",
  "拿盤": "khioh-pôaⁿ",
  "拿碗": "khioh-óaⁿ",
  "拿筷": "khioh-thî",
  "拿匙": "khioh-thng-kí",
  "洗手台": "sé-chhiú-tâi",
  "水龍頭": "chúi-liông-thâu",
  "開水": "khai-chúi",
  "關水": "koan-chúi",
  "水流": "chúi-lâu",
  "水滴": "chúi-tih",
  "水漏": "chúi-lāu",
  "擦乾": "chhit-ta",
  "擦濕": "chhit-sip",
  "擦地": "chhit-tē",
  "地板滑": "tē-pán ku̍t",
  "小心跌": "sió-sim tò",
  "跌倒": "tò-tó",
  "撞到": "chòng-tio̍h",
  "痛痛": "thiànn-thiànn",
  "起來": "khí-lâi",
  "坐好": "chē-hó",
  "躺好": "thn̄g-hó",
  "走好": "kiâⁿ-hó",
  "別動": "bián tōng",
  "動一下": "tōng-chi̍t-ē",
  "抬頭": "thâu-khí",
  "低頭": "kē-thâu",
  "轉頭": "choán-thâu",
  "看左": "khòaⁿ-chó",
  "看右": "khòaⁿ-iū",
  "看上": "khòaⁿ-téng",
  "看下": "khòaⁿ-kē",
  "伸手": "chhun-chhiú",
  "縮手": "sok-chhiú",
  "抬腳": "thâu-kha",
  "放腳": "pàng-kha",
  "腳開": "kha-khai",
  "腳合": "kha-ha̍p",
  "彎腰": "oan-iau",
  "伸直": "chhun-ti̍t",
  "彎腳": "oan-kha",
  "踢": "thá",
  "踩": "chhái",
  "腳酸": "kha-sng",
  "腳麻": "kha-bî",
  "腳抖": "kha-chún",
  "腳冷": "kha-kóng",
  "腳熱": "kha-sio",
  "腳臭": "kha-chhàu",
  "洗腳": "sé-kha",
  "擦腳": "chhit-kha",
  "腳乾": "kha-ta",
  "腳濕": "kha-sip",
  "穿鞋子": "chhēng-ôe-á",
  "脫鞋子": "thng-ôe-á",
  "鞋子髒": "ôe-á ang-chang",
  "擦鞋": "chhit-ôe",
  "鞋子濕": "ôe-á sip",
  "鞋子乾": "ôe-á ta",
  "鞋子臭": "ôe-á chhàu",
  "換鞋": "uā-ôe",
  "拖鞋": "thoa-ôe",
  "穿拖鞋": "chhēng-thoa-ôe",
  "脫拖鞋": "thng-thoa-ôe",
  "襪子髒": "bē-á ang-chang",
  "襪子臭": "bē-á chhàu",
  "換襪子": "uā-bē-á",
  "衣服熱": "saⁿ-khò͘ sio",
  "衣服冷": "saⁿ-khò͘ kóng",
  "衣服大": "saⁿ-khò͘ tōa",
  "衣服小": "saⁿ-khò͘ sió",
  "衣服緊": "saⁿ-khò͘ kín",
  "衣服鬆": "saⁿ-khò͘ sâng",
  "衣服破": "saⁿ-khò͘ phò",
  "衣服掉": "saⁿ-khò͘ tò",
  "衣服臭": "saⁿ-khò͘ chhàu",
  "衣服乾": "saⁿ-khò͘ ta",
  "衣服濕": "saⁿ-khò͘ sip",
  "衣服皺": "saⁿ-khò͘ jiâu",
  "穿上衣": "chhēng-siōng-i",
  "脫上衣": "thng-siōng-i",
  "穿內衣": "chhēng-lāi-i",
  "脫內衣": "thng-lāi-i",
  "穿外套": "chhēng-gōa-thò",
  "脫外套": "thng-gōa-thò",
  "穿毛帽": "chhēng-mô͘-bō",
  "脫毛帽": "thng-mô͘-bō",
  "穿圍巾": "chhēng-ûi-kin",
  "脫圍巾": "thng-ûi-kin",
  "穿手套": "chhēng-chhiú-toh",
  "脫手套": "thng-chhiú-toh",
  "穿雨衣": "chhēng-hō͘-i",
  "脫雨衣": "thng-hō͘-i",
  "拿傘": "khioh-sòaⁿ",
  "撐傘": "chhàng-sòaⁿ",
  "收傘": "siu-sòaⁿ",
  "傘壞": "sòaⁿ-pháiⁿ",
  "傘髒": "sòaⁿ-ang-chang",
  "擦傘": "chhit-sòaⁿ",
  "傘乾": "sòaⁿ-ta",
  "傘濕": "sòaⁿ-sip",
  "拿包": "khioh-pau",
  "背包": "pōe-pau",
  "放包": "pàng-pau",
  "開包": "khai-pau",
  "關包": "koan-pau",
  "包重": "pau-tāng",
  "包輕": "pau-kheng",
  "包髒": "pau-ang-chang",
  "擦包": "chhit-pau",
  "拿錢包": "khioh-chîⁿ-pau",
  "開錢包": "khai-chîⁿ-pau",
  "關錢包": "koan-chîⁿ-pau",
  "拿錢": "khioh-chîⁿ",
  "放錢": "pàng-chîⁿ",
  "錢多": "chîⁿ-chē",
  "錢少": "chîⁿ-chió",
  "沒錢": "bô-chîⁿ",
  "借錢": "chhioh-chîⁿ",
  "還錢": "hôan-chîⁿ",
  "存錢": "chhún-chîⁿ",
  "花錢": "hoe-chîⁿ",
  "省錢": "séng-chîⁿ",
  "浪費": "lông-hùi",
  "拿卡": "khioh-khà",
  "放卡": "pàng-khà",
  "卡壞": "khà-pháiⁿ",
  "卡髒": "khà-ang-chang",
  "擦卡": "chhit-khà",
  "刷卡": "soat-khà",
  "密碼": "bi̍t-bé",
  "輸密碼": "su-bi̍t-bé",
  "忘密碼": "bōng-bi̍t-bé",
  "換卡": "uā-khà",
  "手機": "chhiú-ki",
  "拿手機": "khioh-chhiú-ki",
  "放手機": "pàng-chhiú-ki",
  "開手機": "khai-chhiú-ki",
  "關手機": "koan-chhiú-ki",
  "手機響": "chhiú-ki-siáng",
  "接電話": "chiap-tiān-ōe",
  "掛電話": "kòa-tiān-ōe",
  "打電話": "phah-tiān-ōe",
  "電話號": "tiān-ōe-hō",
  "存號": "chhún-hō",
  "找號": "chhōe-hō",
  "大聲講": "tōa-siaⁿ kóng",
  "小聲講": "sió-siaⁿ kóng",
  "聽不清": "thiaⁿ-bōe-chheng",
  "再講": "chài kóng",
  "講慢點": "kóng bān-chi̍t-ē",
  "講清楚": "kóng chheng-chhó",
  "聽懂": "thiaⁿ-tóng",
  "聽不懂": "thiaⁿ-bōe-tóng",
  "說話": "kóng-ōe",
  "不會說": "bōe-kóng",
  "說不出": "kóng-bōe-chhut",
  "講笑話": "kóng-chhiò-ōe",
  "好笑": "hó-chhiò",
  "不好笑": "bōe-hó-chhiò",
  "開玩笑": "khai-ōan-chhiò",
  "別吵": "bián chhau",
  "安靜點": "an-chēng-chi̍t-ē",
  "別講": "bián kóng",
  "多講": "kīn kóng",
  "少講": "chió kóng",
  "叫人": "kiò-lâng",
  "叫誰": "kiò-siáng",
  "叫醫生": "kiò-i-seng",
  "叫護士": "kiò-hō͘-sū",
  "叫家人": "kiò-ka-jîn",
  "家人來": "ka-jîn lâi",
  "家人走": "ka-jîn khì",
  "想家人": "siūⁿ ka-jîn",
  "想小孩": "siūⁿ sió-hái",
  "想朋友": "siūⁿ pîng-iú",
  "朋友來": "pîng-iú lâi",
  "朋友走": "pîng-iú khì",
  "誰來": "siáng lâi",
  "誰走": "siáng khì",
  "醫生來": "i-seng lâi",
  "醫生走": "i-seng khì",
  "護士來": "hō͘-sū lâi",
  "護士走": "hō͘-sū khì",
  "探病": "thàm-pēⁿ",
  "送花": "sàng-hoe",
  "送水果": "sàng-chhài-kó",
  "送禮": "sàng-lé",
  "謝謝你": "to-siā lí",
  "辛苦": "sin-khó͘",
  "不辛苦": "bōe-sin-khó͘",
  "很辛苦": "kín sin-khó͘",
  "休息下": "hiū-khek-ē",
  "喝水吧": "lim-chúi lah",
  "吃東西": "chia̍h-tōng-sai",
  "吃點心": "chia̍h-tiám-sim",
  "吃糖": "chia̍h-thn̂g",
  "吃餅": "chia̍h-piáⁿ",
  "吃麵包": "chia̍h-mī-pau",
  "喝牛奶": "lim-gû-lin",
  "喝果汁": "lim-kó-chiap",
  "喝茶吧": "lim-tê lah",
  "喝咖啡": "lim-ka-pi",
  "拿糖": "khioh-thn̂g",
  "拿餅": "khioh-piáⁿ",
  "拿麵包": "khioh-mī-pau",
  "甜點": "tiⁿ-tiám",
  "餅乾": "piáⁿ-kan",
  "糖果": "thn̂g-kó",
  "巧克力": "kháu-khek-lí",
  "蛋糕": "kóe",
  "冰淇淋": "peng-kî-lím",
  "布丁": "pù-teng",
  "優格": "iū-kó",
  "果醬": "kó-chiòng",
  "抹醬": "bōa-chiòng",
  "麵包抹醬": "mī-pau bōa-chiòng",
  "吐司": "thú-sū",
  "烤吐司": "khan-thú-sū",
  "三明治": "sann-bî-chì",
  "漢堡": "hàn-pau",
  "熱狗": "sio-káu",
  "薯條": "chîⁿ-thiâu",
  "雞塊": "koe-khoái",
  "披薩": "phì-sat",
  "壽司": "siū-sî",
  "飯團": "pn̄g-thôan",
  "便當": "piān-tong",
  "炒飯": "chhá-pn̄g",
  "燴飯": "ōe-pn̄g",
  "粥": "hê",
  "牛肉湯": "gû-bah-thng",
  "雞湯": "koe-thng",
  "魚湯": "hî-thng",
  "菜湯": "chhài-thng",
  "味噌湯": "bī-so͘-thng",
  "湯熱": "thng-sio",
  "湯冷": "thng-kóng",
  "湯淡": "thng-tām",
  "湯濃": "thng-lông",
  "湯好喝": "thng-hó-lim",
  "湯不好喝": "thng-bōe-hó-lim",
  "湯匙掉": "thng-kí tò",
  "拿湯匙": "khioh-thng-kí",
  "湯灑": "thng-sàn",
  "擦湯": "chhit-thng",
  "湯碗": "thng-óaⁿ",
  "洗湯碗": "sé-thng-óaⁿ",
  "擦湯碗": "chhit-thng-óaⁿ",
  "菜盤": "chhài-pôaⁿ",
  "肉盤": "bah-pôaⁿ",
  "魚盤": "hî-pôaⁿ",
  "水果盤": "chhài-kó-pôaⁿ",
  "洗盤": "sé-pôaⁿ",
  "擦盤": "chhit-pôaⁿ",
  "盤子掉": "pôaⁿ tò",
  "盤子髒": "pôaⁿ ang-chang",
  "盤子乾": "pôaⁿ ta",
  "盤子濕": "pôaⁿ sip",
  "放盤子": "pàng-pôaⁿ",
  "拿盤子": "khioh-pôaⁿ",
  "碗掉": "óaⁿ tò",
  "碗髒": "óaⁿ ang-chang",
  "碗乾": "óaⁿ ta",
  "碗濕": "óaⁿ sip",
  "放碗": "pàng-óaⁿ",
  "筷子掉": "thî tò",
  "筷子髒": "thî ang-chang",
  "筷子乾": "thî ta",
  "筷子濕": "thî sip",
  "放筷子": "pàng-thî",
  "拿筷子": "khioh-thî",
  "湯匙髒": "thng-kí ang-chang",
  "湯匙乾": "thng-kí ta",
  "湯匙濕": "thng-kí sip",
  "放湯匙": "pàng-thng-kí",
  "叉子掉": "chhâ-á tò",
  "叉子髒": "chhâ-á ang-chang",
  "叉子乾": "chhâ-á ta",
  "叉子濕": "chhâ-á sip",
  "放叉子": "pàng-chhâ-á",
  "拿叉子": "khioh-chhâ-á",
  "刀子掉": "to-á tò",
  "刀子髒": "to-á ang-chang",
  "刀子乾": "to-á ta",
  "刀子濕": "to-á sip",
  "放刀子": "pàng-to-á",
  "拿刀子": "khioh-to-á",
  "小心刀": "sió-sim to",
  "刀子利": "to-á lī",
  "刀子鈍": "to-á tūn",
  "切肉": "chhiat-bah",
  "切魚": "chhiat-hî",
  "切慢點": "chhiat bān-chi̍t-ē",
  "別切手": "bián chhiat-chhiú",
  "切到了": "chhiat-tio̍h liáu",
  "流血了": "lâu-hiat liáu",
  "擦血": "chhit-hiat",
  "貼繃": "thiap-pàng",
  "拿繃": "khioh-pàng",
  "換繃": "uā-pàng",
  "繃髒": "pàng-ang-chang",
  "繃濕": "pàng-sip",
  "繃掉了": "pàng tò liáu",
  "傷口痛": "siong-kháu thiànn",
  "傷口紅": "siong-kháu âng",
  "傷口腫": "siong-kháu chhóng",
  "傷口臭": "siong-kháu chhàu",
  "傷口乾": "siong-kháu ta",
  "傷口濕": "siong-kháu sip",
  "擦傷口": "chhit-siong-kháu",
  "傷口好": "siong-kháu hó",
  "傷口壞": "siong-kháu pháiⁿ",
  "傷口癢": "siong-kháu chhiū",
  "別抓": "bián kha",
  "抓傷": "kha-siong",
  "抓破": "kha-phò",
  "抓癢": "kha-chhiū",
  "抓這裡": "kha chia",
  "抓那裡": "kha hia",
  "輕抓": "kheng-kha",
  "重抓": "tāng-kha",
  "抓痛": "kha-thiànn",
  "別碰": "bián pèng",
  "碰痛": "pèng-thiànn",
  "碰這裡": "pèng chia",
  "碰那裡": "pèng hia",
  "輕碰": "kheng-pèng",
  "重碰": "tāng-pèng",
  "碰掉": "pèng-tò",
  "拿棉棒": "khioh-mî-kùn",
  "擦棉棒": "chhit-mî-kùn",
  "棉棒髒": "mî-kùn ang-chang",
  "丟棉棒": "tiāu-mî-kùn",
  "拿棉花": "khioh-mî-hôa",
  "擦棉花": "chhit-mî-hôa",
  "棉花髒": "mî-hôa ang-chang",
  "丟棉花": "tiāu-mî-hôa",
  "拿藥水": "khioh-io̍h-chúi",
  "擦藥水": "chhit-io̍h-chúi",
  "藥水臭": "io̍h-chúi chhàu",
  "藥水冷": "io̍h-chúi kóng",
  "藥水熱": "io̍h-chúi sio",
  "藥水痛": "io̍h-chúi thiànn",
  "藥水癢": "io̍h-chúi chhiū",
  "藥水紅": "io̍h-chúi âng",
  "藥水掉": "io̍h-chúi tò",
  "擦乾淨": "chhit-kan-cheng",
  "藥膏臭": "io̍h-kô chhàu",
  "藥膏冷": "io̍h-kô kóng",
  "藥膏熱": "io̍h-kô sio",
  "藥膏痛": "io̍h-kô thiànn",
  "藥膏癢": "io̍h-kô chhiū",
  "藥膏紅": "io̍h-kô âng",
  "藥膏掉": "io̍h-kô tò",
  "拿藥布": "khioh-io̍h-pò͘",
  "換藥布": "uā-io̍h-pò͘",
  "藥布髒": "io̍h-pò͘ ang-chang",
  "藥布濕": "io̍h-pò͘ sip",
  "藥布掉": "io̍h-pò͘ tò",
  "藥布痛": "io̍h-pò͘ thiànn",
  "藥布癢": "io̍h-pò͘ chhiū",
  "藥布紅": "io̍h-pò͘ âng",
  "撕藥布": "si-io̍h-pò͘",
  "撕痛": "si-thiànn",
  "輕撕": "kheng-si",
  "重撕": "tāng-si",
  "拿藥丸": "khioh-io̍h-oân",
  "吃藥丸": "chia̍h-io̍h-oân",
  "吞藥丸": "thun-io̍h-oân",
  "藥丸苦": "io̍h-oân khó͘",
  "藥丸甜": "io̍h-oân tiⁿ",
  "藥丸臭": "io̍h-oân chhàu",
  "藥丸大": "io̍h-oân tōa",
  "藥丸小": "io̍h-oân sió",
  "藥丸掉": "io̍h-oân tò",
  "撿藥丸": "kéng-io̍h-oân",
  "藥丸髒": "io̍h-oân ang-chang",
  "藥丸乾": "io̍h-oân ta",
  "藥丸濕": "io̍h-oân sip",
  "吃幾顆": "chia̍h kúi-lia̍p",
  "吃一顆": "chia̍h chi̍t-lia̍p",
  "吃兩顆": "chia̍h nn̄g-lia̍p",
  "吃三顆": "chia̍h sann-lia̍p",
  "吞不下": "thun-bōe-lo̍h",
  "藥卡喉": "io̍h-khà-âu",
  "喝水吞": "lim-chúi thun",
  "吐藥丸": "thò͘-io̍h-oân",
  "藥丸多": "io̍h-oân chē",
  "藥丸少": "io̍h-oân chió",
  "藥丸夠": "io̍h-oân kàu",
  "藥丸不夠": "io̍h-oân bōe-kàu",
  "拿藥袋": "khioh-io̍h-tē",
  "放藥袋": "pàng-io̍h-tē",
  "藥袋髒": "io̍h-tē ang-chang",
  "藥袋破": "io̍h-tē phò",
  "換藥袋": "uā-io̍h-tē",
  "藥袋滿": "io̍h-tē bóa",
  "藥袋空": "io̍h-tē khang",
  "藥袋掉": "io̍h-tē tò",
  "撿藥袋": "kéng-io̍h-tē",
  "量溫度": "niû-un-tō͘",
  "拿溫度計": "khioh-un-tō͘-kè",
  "放溫度計": "pàng-un-tō͘-kè",
  "溫度計掉": "un-tō͘-kè tò",
  "撿溫度計": "kéng-un-tō͘-kè",
  "溫度計髒": "un-tō͘-kè ang-chang",
  "擦溫度計": "chhit-un-tō͘-kè",
  "溫度高": "un-tō͘ ko",
  "溫度低": "un-tō͘ kē",
  "發燒了": "hoat-sio liáu",
  "退燒了": "thè-sio liáu",
  "拿血壓計": "khioh-hiat-ap-kè",
  "放血壓計": "pàng-hiat-ap-kè",
  "血壓計掉": "hiat-ap-kè tò",
  "撿血壓計": "kéng-hiat-ap-kè",
  "血壓計髒": "hiat-ap-kè ang-chang",
  "擦血壓計": "chhit-hiat-ap-kè",
  "血壓高": "hiat-ap ko",
  "血壓低": "hiat-ap kē",
  "血壓好": "hiat-ap hó",
  "血壓壞": "hiat-ap pháiⁿ",
  "戴血壓計": "tì-hiat-ap-kè",
  "脫血壓計": "thng-hiat-ap-kè",
  "血壓計緊": "hiat-ap-kè kín",
  "血壓計鬆": "hiat-ap-kè sâng",
  "量脈搏": "niû-me̍h-poh",
  "脈搏快": "me̍h-poh khoài",
  "脈搏慢": "me̍h-poh bān",
  "脈搏好": "me̍h-poh hó",
  "脈搏壞": "me̍h-poh pháiⁿ",
  "量體重": "niû-thé-thòng",
  "拿體重計": "khioh-thé-thòng-kè",
  "放體重計": "pàng-thé-thòng-kè",
  "體重計掉": "thé-thòng-kè tò",
  "撿體重計": "kéng-thé-thòng-kè",
  "體重計髒": "thé-thòng-kè ang-chang",
  "擦體重計": "chhit-thé-thòng-kè",
  "體重多": "thé-thòng chē",
  "體重少": "thé-thòng chió",
  "胖了": "pûi liáu",
  "瘦了": "sán liáu",
  "站上去": "khí-téng-khì",
  "下來": "lo̍h-lâi",
  "別搖": "bián iô",
  "站穩": "khí-ún",
  "扶好": "pû-hó",
  "量身高": "niû-sin-kau",
  "身高計": "sin-kau-kè",
  "站直": "khí-ti̍t",
  "別彎": "bián oan",
  "身高多": "sin-kau chē",
  "身高少": "sin-kau chió",
  "長高": "tn̂g-ko",
  "縮水": "sok-chúi",
  "拿輪椅": "khioh-lûn-í",
  "推輪椅": "thui-lûn-í",
  "坐輪椅": "chē-lûn-í",
  "輪椅髒": "lûn-í ang-chang",
  "擦輪椅": "chhit-lûn-í",
  "輪椅壞": "lûn-í pháiⁿ",
  "輪椅穩": "lûn-í ún",
  "輪椅搖": "lûn-í iô",
  "輪椅煞": "lûn-í sat",
  "拿助行器": "khioh-tsō-hîng-khì",
  "用助行器": "iōng-tsō-hîng-khì",
  "助行器髒": "tsō-hîng-khì ang-chang",
  "擦助行器": "chhit-tsō-hîng-khì",
  "助行器壞": "tsō-hîng-khì pháiⁿ",
  "助行器穩": "tsō-hîng-khì ún",
  "助行器搖": "tsō-hîng-khì iô",
  "拿拐杖": "khioh-kuá-tsiùnn",
  "用拐杖": "iōng-kuá-tsiùnn",
  "拐杖髒": "kuá-tsiùnn ang-chang",
  "擦拐杖": "chhit-kuá-tsiùnn",
  "拐杖壞": "kuá-tsiùnn pháiⁿ",
  "拐杖穩": "kuá-tsiùnn ún",
  "拐杖搖": "kuá-tsiùnn iô",
  "拐杖掉": "kuá-tsiùnn tò",
  "撿拐杖": "kéng-kuá-tsiùnn",
  "拿床墊": "khioh-chhn̂g-tiām",
  "鋪床墊": "phou-chhn̂g-tiām",
  "換床墊": "uā-chhn̂g-tiām",
  "床墊髒": "chhn̂g-tiām ang-chang",
  "床墊臭": "chhn̂g-tiām chhàu",
  "床墊濕": "chhn̂g-tiām sip",
  "床墊乾": "chhn̂g-tiām ta",
  "床墊軟": "chhn̂g-tiām nńg",
  "床墊硬": "chhn̂g-tiām ngē",
  "拿床單": "khioh-chhn̂g-toaⁿ",
  "鋪床單": "phou-chhn̂g-toaⁿ",
  "換床單": "uā-chhn̂g-toaⁿ",
  "床單髒": "chhn̂g-toaⁿ ang-chang",
  "床單臭": "chhn̂g-toaⁿ chhàu",
  "床單濕": "chhn̂g-toaⁿ sip",
  "床單乾": "chhn̂g-toaⁿ ta",
  "床單皺": "chhn̂g-toaⁿ jiâu",
  "床單掉": "chhn̂g-toaⁿ tò",
  "拿被子": "khioh-phōe",
  "換被子": "uā-phōe",
  "被子髒": "phōe ang-chang",
  "被子臭": "phōe chhàu",
  "被子濕": "phōe sip",
  "被子乾": "phōe ta",
  "被子重": "phōe tāng",
  "被子輕": "phōe kheng",
  "被子熱": "phōe sio",
  "被子冷": "phōe kóng",
  "被子掉": "phōe tò",
  "蓋毛毯": "kòa-mô͘-thán",
  "換毛毯": "uā-mô͘-thán",
  "毛毯髒": "mô͘-thán ang-chang",
  "毛毯臭": "mô͘-thán chhàu",
  "毛毯濕": "mô͘-thán sip",
  "毛毯乾": "mô͘-thán ta",
  "毛毯重": "mô͘-thán tāng",
  "毛毯輕": "mô͘-thán kheng",
  "毛毯熱": "mô͘-thán sio",
  "毛毯冷": "mô͘-thán kóng",
  "毛毯掉": "mô͘-thán tò",
  "拿枕頭": "khioh-chím-thâu",
  "放枕頭": "pàng-chím-thâu",
  "換枕頭": "uā-chím-thâu",
  "枕頭髒": "chím-thâu ang-chang",
  "枕頭臭": "chím-thâu chhàu",
  "枕頭濕": "chím-thâu sip",
  "枕頭乾": "chím-thâu ta",
  "枕頭軟": "chím-thâu nńg",
  "枕頭硬": "chím-thâu ngē",
  "枕頭高": "chím-thâu ko",
  "枕頭低": "chím-thâu kē",
  "枕頭掉": "chím-thâu tò",
  "撿枕頭": "kéng-chím-thâu",
  "拿床": "khioh-chhn̂g",
  "換床": "uā-chhn̂g",
  "床髒": "chhn̂g ang-chang",
  "床臭": "chhn̂g chhàu",
  "床濕": "chhn̂g sip",
  "床乾": "chhn̂g ta",
  "床硬": "chhn̂g ngē",
  "床軟": "chhn̂g nńg",
  "床高": "chhn̂g ko",
  "床低": "chhn̂g kē",
  "床穩": "chhn̂g ún",
  "床搖": "chhn̂g iô",
  "床壞": "chhn̂g pháiⁿ",
  "擦床": "chhit-chhn̂g",
  "床頭": "chhn̂g-thâu",
  "床尾": "chhn̂g-bóe",
  "床邊": "chhn̂g-pêng",
  "床下": "chhn̂g-kē",
  "床角": "chhn̂g-kak",
  "床欄": "chhn̂g-lân",
  "床欄高": "chhn̂g-lân ko",
  "床欄低": "chhn̂g-lân kē",
  "床欄穩": "chhn̂g-lân ún",
  "床欄搖": "chhn̂g-lân iô",
  "床欄壞": "chhn̂g-lân pháiⁿ",
  "住院": "chū-iⁿ",
  "出院": "chhut-iⁿ",
  "病房": "pēⁿ-pâng",
  "病床": "pēⁿ-chhn̂g",
  "病房髒": "pēⁿ-pâng ang-chang",
  "病房臭": "pēⁿ-pâng chhàu",
  "病房熱": "pēⁿ-pâng sio",
  "病房冷": "pēⁿ-pâng kóng",
  "病房吵": "pēⁿ-pâng chhau",
  "病房靜": "pēⁿ-pâng chēng",
  "病房門": "pēⁿ-pâng mn̂g",
  "開病房門": "khai-pēⁿ-pâng-mn̂g",
  "關病房門": "koan-pēⁿ-pâng-mn̂g",
  "病房窗": "pēⁿ-pâng thang",
  "開病房窗": "khai-pēⁿ-pâng-thang",
  "關病房窗": "koan-pēⁿ-pâng-thang",
  "病房燈": "pēⁿ-pâng teng",
  "開病房燈": "khai-pēⁿ-pâng-teng",
  "關病房燈": "koan-pēⁿ-pâng-teng",
  "病房冷氣": "pēⁿ-pâng léng-khì",
  "病房電扇": "pēⁿ-pâng tiān-sì",
  "病房電視": "pēⁿ-pâng tiān-sī",
  "病房桌": "pēⁿ-pâng toh",
  "病房椅": "pēⁿ-pâng í-á",
  "病房櫃": "pēⁿ-pâng kūi",
  "病房床": "pēⁿ-pâng chhn̂g",
  "換病房": "uā-pēⁿ-pâng",
  "清病房": "chheng-pēⁿ-pâng",
  "病房號": "pēⁿ-pâng hō",
  "病房樓": "pēⁿ-pâng lâu",
  "住院單": "chū-iⁿ-toaⁿ",
  "拿住院單": "khioh-chū-iⁿ-toaⁿ",
  "填住院單": "thian-chū-iⁿ-toaⁿ",
  "交住院單": "kau-chū-iⁿ-toaⁿ",
  "住院費": "chū-iⁿ-hùi",
  "付住院費": "hù-chū-iⁿ-hùi",
  "住院天": "chū-iⁿ-thiⁿ",
  "住院幾天": "chū-iⁿ kúi-thiⁿ",
  "住院久": "chū-iⁿ kú",
  "出院單": "chhut-iⁿ-toaⁿ",
  "拿出院單": "khioh-chhut-iⁿ-toaⁿ",
  "填出院單": "thian-chhut-iⁿ-toaⁿ",
  "交出院單": "kau-chhut-iⁿ-toaⁿ",
  "出院費": "chhut-iⁿ-hùi",
  "付出院費": "hù-chhut-iⁿ-hùi",
  "病歷": "pēⁿ-le̍k",
  "拿病歷": "khioh-pēⁿ-le̍k",
  "看病歷": "khòaⁿ-pēⁿ-le̍k",
  "病歷號": "pēⁿ-le̍k-hō",
  "病歷袋": "pēⁿ-le̍k-tē",
  "醫生看": "i-seng khòaⁿ",
  "醫生問": "i-seng mn̄g",
  "醫生講": "i-seng kóng",
  "醫生查": "i-seng chhâ",
  "醫生寫": "i-seng siá",
  "護士量": "hō͘-sū niû",
  "護士擦": "hō͘-sū chhit",
  "護士換": "hō͘-sū uā",
  "護士拿": "hō͘-sū khioh",
  "護士問": "hō͘-sū mn̄g",
  "病友": "pēⁿ-iú",
  "病友來": "pēⁿ-iú lâi",
  "病友走": "pēⁿ-iú khì",
  "病友講": "pēⁿ-iú kóng",
  "病友笑": "pēⁿ-iú chhiò",
  "病友哭": "pēⁿ-iú khàu",
  "病友睡": "pēⁿ-iú khùn",
  "病友吵": "pēⁿ-iú chhau",
  "病友好": "pēⁿ-iú hó",
  "病友壞": "pēⁿ-iú pháiⁿ",
  "病房規矩": "pēⁿ-pâng kui-kí",
  "別吵病友": "bián chhau-pēⁿ-iú",
  "住院藥": "chū-iⁿ-io̍h",
  "吃住院藥": "chia̍h-chū-iⁿ-io̍h",
  "住院藥多": "chū-iⁿ-io̍h chē",
  "住院藥少": "chū-iⁿ-io̍h chió",
  "住院藥苦": "chū-iⁿ-io̍h khó͘",
  "住院藥甜": "chū-iⁿ-io̍h tiⁿ",
  "住院藥臭": "chū-iⁿ-io̍h chhàu",
  "住院藥掉": "chū-iⁿ-io̍h tò",
  "住院藥髒": "chū-iⁿ-io̍h ang-chang",
  "住院藥單": "chū-iⁿ-io̍h-toaⁿ",
  "拿藥單": "khioh-io̍h-toaⁿ",
  "看藥單": "khòaⁿ-io̍h-toaⁿ",
  "交藥單": "kau-io̍h-toaⁿ",
  "藥單錯": "io̍h-toaⁿ chhò",
  "藥單對": "io̍h-toaⁿ tùi",
  "藥單掉": "io̍h-toaⁿ tò",
  "撿藥單": "kéng-io̍h-toaⁿ",
  "藥局": "io̍h-kio̍k",
  "去藥局": "khì io̍h-kio̍k",
  "藥局遠": "io̍h-kio̍k hn̄g",
  "藥局近": "io̍h-kio̍k kīn",
  "藥局開": "io̍h-kio̍k khai",
  "藥局關": "io̍h-kio̍k koan",
  "拿藥包": "khioh-io̍h-pau",
  "藥包多": "io̍h-pau chē",
  "藥包少": "io̍h-pau chió",
  "藥包掉": "io̍h-pau tò",
  "撿藥包": "kéng-io̍h-pau",
  "藥包髒": "io̍h-pau ang-chang",
  "藥包破": "io̍h-pau phò",
  "住院檢查": "chū-iⁿ kiám-chha",
  "檢查單": "kiám-chha-toaⁿ",
  "拿檢查單": "khioh-kiám-chha-toaⁿ",
  "交檢查單": "kau-kiám-chha-toaⁿ",
  "檢查室": "kiám-chha-sek",
  "去檢查室": "khì kiám-chha-sek",
  "檢查痛": "kiám-chha thiànn",
  "檢查冷": "kiám-chha kóng",
  "檢查熱": "kiám-chha sio",
  "檢查久": "kiám-chha kú",
  "檢查快": "kiám-chha khoài",
  "檢查好": "kiám-chha hó",
  "檢查壞": "kiám-chha pháiⁿ",
  "檢查報告": "kiám-chha pò-kò",
  "拿報告": "khioh-pò-kò",
  "看報告": "khòaⁿ-pò-kò",
  "報告好": "pò-kò hó",
  "報告壞": "pò-kò pháiⁿ",
  "報告掉": "pò-kò tò",
  "撿報告": "kéng-pò-kò",
  "住院針": "chū-iⁿ-chiam",
  "打針": "phah-chiam",
  "打針痛": "phah-chiam thiànn",
  "打針紅": "phah-chiam âng",
  "打針腫": "phah-chiam chhóng",
  "打針癢": "phah-chiam chhiū",
  "打針冷": "phah-chiam kóng",
  "打針熱": "phah-chiam sio",
  "打針快": "phah-chiam khoài",
  "打針慢": "phah-chiam bān",
  "打針好": "phah-chiam hó",
  "打針壞": "phah-chiam pháiⁿ",
  "針頭": "chiam-thâu",
  "針頭掉": "chiam-thâu tò",
  "撿針頭": "kéng-chiam-thâu",
  "針頭髒": "chiam-thâu ang-chang",
  "丟針頭": "tiāu-chiam-thâu",
  "點滴": "tiám-tih",
  "掛點滴": "kòa-tiám-tih",
  "換點滴": "uā-tiám-tih",
  "點滴冷": "tiám-tih kóng",
  "點滴熱": "tiám-tih sio",
  "點滴快": "tiám-tih khoài",
  "點滴慢": "tiám-tih bān",
  "點滴痛": "tiám-tih thiànn",
  "點滴紅": "tiám-tih âng",
  "點滴腫": "tiám-tih chhóng",
  "點滴癢": "tiám-tih chhiū",
  "點滴完": "tiám-tih oân",
  "點滴漏": "tiám-tih lāu",
  "點滴掉": "tiám-tih tò",
  "點滴管": "tiám-tih-kóng",
  "點滴管壞": "tiám-tih-kóng pháiⁿ",
  "點滴管堵": "tiám-tih-kóng sái",
  "點滴管掉": "tiám-tih-kóng tò",
  "撿點滴管": "kéng-tiám-tih-kóng",
  "急救": "kín-kiù",
  "救命": "kiù-miā",
  "快救": "khoài kiù",
  "叫救護車": "kiò kiù-hō͘-chhia",
  "救護車來": "kiù-hō͘-chhia lâi",
  "救護車走": "kiù-hō͘-chhia khì",
  "救護車快": "kiù-hō͘-chhia khoài",
  "救護車慢": "kiù-hō͘-chhia bān",
  "救護車到": "kiù-hō͘-chhia kàu",
  "緊急": "kín-ki̍p",
  "很急": "kín ki̍p",
  "快點": "khoài-chi̍t-ē",
  "趕快來": "kín-khoài lâi",
  "趕快走": "kín-khoài khì",
  "趕快拿": "kín-khoài khioh",
  "趕快打": "kín-khoài phah",
  "打119": "phah it-it-kiú",
  "打電話救": "phah-tiān-ōe kiù",
  "快叫人": "khoài kiò-lâng",
  "叫急救": "kiò kín-kiù",
  "叫醫生快": "kiò i-seng khoài",
  "叫護士快": "kiò hō͘-sū khoài",
  "快幫忙": "khoài pang-bâng",
  "快救我": "khoài kiù góa",
  "快扶我": "khoài pû góa",
  "快抱我": "khoài phō góa",
  "快推我": "khoài thui góa",
  "快拉我": "khoài lā góa",
  "不行了": "bōe-hêng liáu",
  "喘不過": "chhoán-bōe-kòe",
  "沒氣了": "bô-khì liáu",
  "心跳快": "sim-tō khoài",
  "心跳停": "sim-tō thêng",
  "昏倒": "hun-tó",
  "暈了": "tàng liáu",
  "摔倒": "sok-tó",
  "撞頭": "chòng-thâu",
  "撞手": "chòng-chhiú",
  "撞腳": "chòng-kha",
  "撞背": "chòng-pūi",
  "撞痛": "chòng-thiànn",
  "流血多": "lâu-hiat chē",
  "流血停": "lâu-hiat thêng",
  "血流快": "hiat lâu khoài",
  "血流慢": "hiat lâu bān",
  "壓住": "ap-tī",
  "壓血": "ap-hiat",
  "包住": "pau-tī",
  "包傷口": "pau-siong-kháu",
  "拿布": "khioh-pò͘",
  "包布": "pau-pò͘",
  "綁布": "páng-pò͘",
  "綁緊": "páng-kín",
  "綁鬆": "páng-sâng",
  "綁痛": "páng-thiànn",
  "綁掉": "páng-tò",
  "換布": "uā-pò͘",
  "布髒": "pò͘ ang-chang",
  "布濕": "pò͘ sip",
  "布乾": "pò͘ ta",
  "布破": "pò͘ phò",
  "擦血布": "chhit-hiat-pò͘",
  "丟血布": "tiāu-hiat-pò͘",
  "傷口大": "siong-kháu tōa",
  "傷口小": "siong-kháu sió",
  "傷口深": "siong-kháu chhim",
  "傷口淺": "siong-kháu chhian",
  "傷口流血": "siong-kháu lâu-hiat",
  "傷口化膿": "siong-kháu hòe-lâng",
  "傷口感染": "siong-kháu kám-jiám",
  "傷口很痛": "siong-kháu kín thiànn",
  "傷口很癢": "siong-kháu kín chhiū",
  "傷口很紅": "siong-kháu kín âng",
  "傷口很腫": "siong-kháu kín chhóng",
  "傷口很臭": "siong-kháu kín chhàu",
  "傷口很熱": "siong-kháu kín sio",
  "傷口很冷": "siong-kháu kín kóng",
  "傷口乾掉": "siong-kháu ta-tiāu",
  "傷口結痂": "siong-kháu kiat-kha",
  "傷口癒合": "siong-kháu iū-ha̍p",
  "傷口好慢": "siong-kháu hó bān",
  "傷口好快": "siong-kháu hó khoài",
  "傷口不好": "siong-kháu bōe-hó",
  "緊急藥": "kín-ki̍p io̍h",
  "拿緊急藥": "khioh kín-ki̍p io̍h",
  "吃緊急藥": "chia̍h kín-ki̍p io̍h",
  "緊急藥苦": "kín-ki̍p io̍h khó͘",
  "緊急藥甜": "kín-ki̍p io̍h tiⁿ",
  "緊急藥臭": "kín-ki̍p io̍h chhàu",
  "緊急藥掉": "kín-ki̍p io̍h tò",
  "撿緊急藥": "kéng kín-ki̍p io̍h",
  "緊急藥多": "kín-ki̍p io̍h chē",
  "緊急藥少": "kín-ki̍p io̍h chió",
  "緊急藥夠": "kín-ki̍p io̍h kàu",
  "緊急藥不夠": "kín-ki̍p io̍h bōe-kàu",
  "緊急針": "kín-ki̍p chiam",
  "打緊急針": "phah kín-ki̍p chiam",
  "緊急針痛": "kín-ki̍p chiam thiànn",
  "緊急針紅": "kín-ki̍p chiam âng",
  "緊急針腫": "kín-ki̍p chiam chhóng",
  "緊急針癢": "kín-ki̍p chiam chhiū",
  "緊急針冷": "kín-ki̍p chiam kóng",
  "緊急針熱": "kín-ki̍p chiam sio",
  "緊急針快": "kín-ki̍p chiam khoài",
  "緊急針慢": "kín-ki̍p chiam bān",
  "緊急針好": "kín-ki̍p chiam hó",
  "緊急針壞": "kín-ki̍p chiam pháiⁿ",
  "緊急點滴": "kín-ki̍p tiám-tih",
  "掛緊急點滴": "kòa kín-ki̍p tiám-tih",
  "換緊急點滴": "uā kín-ki̍p tiám-tih",
  "緊急點滴冷": "kín-ki̍p tiám-tih kóng",
  "緊急點滴熱": "kín-ki̍p tiám-tih sio",
  "緊急點滴快": "kín-ki̍p tiám-tih khoài",
  "緊急點滴慢": "kín-ki̍p tiám-tih bān",
  "緊急點滴痛": "kín-ki̍p tiám-tih thiànn",
  "緊急點滴紅": "kín-ki̍p tiám-tih âng",
  "緊急點滴腫": "kín-ki̍p tiám-tih chhóng",
  "緊急點滴癢": "kín-ki̍p tiám-tih chhiū",
  "緊急點滴完": "kín-ki̍p tiám-tih oân",
  "緊急點滴漏": "kín-ki̍p tiám-tih lāu",
  "緊急點滴掉": "kín-ki̍p tiám-tih tò",
  "急救包": "kín-kiù-pau",
  "拿急救包": "khioh kín-kiù-pau",
  "開急救包": "khai kín-kiù-pau",
  "關急救包": "koan kín-kiù-pau",
  "急救包髒": "kín-kiù-pau ang-chang",
  "急救包破": "kín-kiù-pau phò",
  "急救包掉": "kín-kiù-pau tò",
  "撿急救包": "kéng kín-kiù-pau",
  "急救藥": "kín-kiù io̍h",
  "拿急救藥": "khioh kín-kiù io̍h",
  "吃急救藥": "chia̍h kín-kiù io̍h",
  "急救藥苦": "kín-kiù io̍h khó͘",
  "急救藥甜": "kín-kiù io̍h tiⁿ",
  "急救藥臭": "kín-kiù io̍h chhàu",
  "急救藥掉": "kín-kiù io̍h tò",
  "撿急救藥": "kéng kín-kiù io̍h",
  "急救布": "kín-kiù pò͘",
  "拿急救布": "khioh kín-kiù pò͘",
  "包急救布": "pau kín-kiù pò͘",
  "綁急救布": "páng kín-kiù pò͘",
  "急救布髒": "kín-kiù pò͘ ang-chang",
  "急救布濕": "kín-kiù pò͘ sip",
  "急救布乾": "kín-kiù pò͘ ta",
  "急救布破": "kín-kiù pò͘ phò",
  "急救布掉": "kín-kiù pò͘ tò",
  "撿急救布": "kéng kín-kiù pò͘",
  "急救棉": "kín-kiù mî-hôa",
  "拿急救棉": "khioh kín-kiù mî-hôa",
  "擦急救棉": "chhit kín-kiù mî-hôa",
  "急救棉髒": "kín-kiù mî-hôa ang-chang",
  "丟急救棉": "tiāu kín-kiù mî-hôa",
  "沒有": "bô",
  "票": "pìnn",
  "你好": "lí-hó",
  "很": "hín",
  "是": "sī",
  "我": "guá",
  "喜歡": "hi-hoan",
  "飯": "pn̄g",
  "喝": "lim",
  "水": "tsuí",
  "去": "khì",
  "來": "lâi",
  "朋友": "pêng-iú",
  "什麼": "sím-mih",
  "怎麼": "tsái-iūⁿ",
  "不行": "bē-sái",
  "多少": "kúi-tsoē",
  "星期": "seng-kî",
  "一": "tsi̍t",
  "二": "jī",
  "三": "sann",
  "四": "sì",
  "五": "gō",
  "六": "la̍k",
  "七": "chhit",
  "八": "peih",
  "九": "káu",
  "十": "tsa̍p",
  "快樂": "khòai-lo̍k",
  "工作": "kang-tsoh",
  "學習": "ha̍k-si̍p",
  "學校": "ha̍k-hāu",
  "老師": "lāu-su",
  "學生": "ha̍k-seng",
  "家人": "ka-jîn",
  "爸爸": "pē",
  "媽媽": "bú",
  "哥哥": "ko-ko",
  "姐姐": "tsí-tsí",
  "弟弟": "tī-tī",
  "妹妹": "mōe-mōe",
  "胃痛": "uì-thòng",
  "骨折": "kut-tit",
  "扶我一下": "phok gua chit e",
  "需要幫忙": "su iunn pang bōng",
  "急診": "kip-tsîm",
  "手術": "tshiu-sut",
  "復健": "hok-kiān",
  "診所": "chhìn-sok",
  "醫院": "īⁿ-īⁿ",
  "護士": "ho͘-sū",
  "醫生": "i-sin",
  "病人": "pēnn-jîn",
  "午安": "ngóo an",
  "我肚子餓": "gua7 tu7 tsi2 gu2",
  "我很累": "gua2 hin2 kui3",
  "幫我一下": "pang gua chit e",
  "可以坐嗎": "kāi-á tsē bē",
  "廁所在哪": "chhù-só tī tó-uī",
  "水在哪裡": "chúi tī tó-uī",
  "要幾點": "ioh kúi tiám",
  "現在幾點": "tān-tsài kúi-tiám",
  "怎麼走": "tsánn-mn̄g tsáu",
  "我不懂": "gua7 m7 tong7",
  "這是什麼": "tse sī siánn-mih",
  "不要": "bô ia̍h bē",
  "你好嗎": "lí hó bō",
  "我很好": "gua2 han2 ho2",
  "你叫什麼名字": "li kiò sió mīng",
  "我叫小明": "gua7 kio3 siau2 beng5",
  "你幾歲": "li ki gua",
  "我住這裡": "gua7 tu7 chit8-le7",
  "你哪裡不舒服": "li tó-uī bô sióng-khóu",
  "你會說台語嗎": "li ho e kong tai gi bo",
  "慢慢說": "bān bān kóng",
  "再說一次": "tsài kóng tsi̍t ē",
  "不客氣": "m̄-kè-ki",
  "請幫忙": "tshing pang-bang",
  "請進": "tshing tsìn",
  "請坐": "chhēng-chēng",
  "請等等": "tshing tánn-tsē",
  "不要緊張": "mài kīn-tsiông",
  "不用擔心": "bô iánn-sim",
  "吃飽了嗎": "chia̍h pá--ah bō",
  "我還沒吃": "gua2 han2-be7 chiah8",
  "要辣嗎": "beh la̍t--bē",
  "不要太鹹": "mài tsài iâm",
  "多一點": "to tsi̍t tiám",
  "少一點": "sió tsi̍t tiám",
  "請給我水": "chhiú kàu guá tsuí",
  "請給我筷子": "chhiáⁿ kā guá kńg-á",
  "我不吃肉": "gua bē chia̍h bah",
  "我吃素": "gua7 chiah8 chhou3",
  "過敏": "koh-lín",
  "海鮮": "hái-sian",
  "花生": "hua-senn",
  "雞蛋": "ke-nn̄g",
  "麵包": "mī-pau",
  "休息": "hiu-sik",
  "打開": "tá-khui",
  "關掉": "kuan3 tioh4",
  "看醫生": "khuànn i-sin",
  "喝藥": "lim io̍h",
  "拿東西": "nâ tōng-sìng",
  "走這邊": "tsáu tsit-pian",
  "進來": "tsìn-lâi",
  "躺下": "tháng--ah",
  "窗戶": "tshng-hù",
  "床": "chhâng",
  "椅子": "iá-á",
  "桌子": "toh8-tsuann5",
  "燈": "teng",
  "冷氣": "lêng-khì",
  "電視": "tiān-sī",
  "電腦": "tiān-náu",
  "洗衣機": "sé-i-ki",
  "電風扇": "tiān-hong-sian",
  "衣服": "i-pang",
  "鞋子": "ê-á",
  "便盆": "piān-pûn",
  "尿布": "jiau-pòo",
  "喘不過氣": "tshuàn bô khì",
  "嘔吐": "au3 tho3",
  "抽筋": "tshiau-kun",
  "紅腫": "âng-tsiúnn",
  "發炎": "hoat-iân",
  "肺炎": "phāi-iân",
  "糖尿病": "tông-lō͘-pēnn",
  "我很開心": "gua2 hin1 khui1-sim1",
  "我很難過": "gua2 hin2 lan2 koa3",
  "很不舒服": "hîn bô sū khì",
  "我怕": "gua2 pha3",
  "我緊張": "gua2 kin2-tsiann5",
  "我想家": "gua2 siunn7 ka1",
  "我想睡覺": "gua siunnn khunnnn",
  "我想哭": "gua siunn khì",
  "阿嬤": "a-má",
  "阿公": "a-kong",
  "姊姊": "tsí-tsí",
  "孩子": "kiánn-á",
  "孫子": "sun tsú",
  "前面": "tî-tsîng",
  "後面": "āu-bīn",
  "左邊": "tso͘-pinn",
  "右邊": "tāi-pêng",
  "上面": "siōng-piⁿ",
  "下面": "ē-po͘",
  "幾天": "kúi tsing",
  "馬上": "bé-siōng",
  "等等": "tánn-tánn",
  "多久": "tó-kú",
  "很久": "hún-kú",
  "一下子": "tsi̍t-ē-á",
  "五分鐘": "gō͘ hun-cheng",
  "等車": "tánn tshia",
  "搭計程車": "tha kah chhia",
  "去醫院": "khì īⁿ-īⁿ-uân",
  "找人": "chhōe-lâng",
  "幫我叫人": "pang gua kio lang",
  "火災": "hué-sai",
  "我肚子痛": "gua7 tou7-tsi7 thang3",
  "我不能走": "gua bē tsáu",
  "我有過敏": "gua u koe-bin",
  "我吃藥過了": "gua7 chiah8 ioh8 koa3--ah4",
  "我有發燒": "gua2 u7 hoat4-sioh4",
  "我想要休息": "gua2 siunn7 beh4 hioh8-sik4",
  "請幫我翻身": "chhiúⁿ pang guá thoan-sin",
  "我要去廁所": "gua beh khi chhù-só",
  "我不想吃": "gua bô siūnn chia̍h",
  "我想洗澡": "gua siunn se3 tsa7",
  "呼吸困難": "hoo-khik khun-lōo",
  "皮膚癢": "phu-kho͘ iáⁿ",
  "咬到舌頭": "ngáu kah tsioh nn̂g",
  "牙齒痛": "gê-thih-thòng",
  "我要喝水": "gua beh lim tsui",
  "幫我拿藥": "pang gua na be̍h",
  "打開冷氣": "tá-khui líng-khì",
  "幫我關燈": "pang gua koan teng",
  "幫我穿衣服": "pang gua chhng i tshing",
  "請幫我扶起來": "chhiáⁿ pang guá phó͘ khí--lâi",
  "我想吃飯": "gua2 siunn7 chia̍h pn̄g",
  "我要躺下": "gua beh tn̂g--hāu",
  "我想坐起來": "gua2 siunn7 chhiah8--khí5 lâi5",
  "我想換衣服": "gua2 siunn7 uann7 i1-huann5",
  "請幫我移動": "chhiáⁿ pang guá î-tōng",
  "我不想吃藥": "gua bô siūnn chia̍h io̍h",
  "我很痛": "gua2 hin2 thang3",
  "我很不舒服": "gua2 hin1 put4 siu3hun3",
  "台北": "Tâi-pak",
  "新北": "Sin-pak",
  "桃園": "Tô-oân",
  "新竹": "Sin-tek",
  "苗栗": "Biâu-li̍k",
  "台中": "Tâi-tiong",
  "彰化": "Tiong-hua",
  "南投": "Lâm-tó",
  "雲林": "Hun-lîm",
  "嘉義": "Ka-gī",
  "台南": "Tâi-lâm",
  "高雄": "Kaohsiung",
  "屏東": "Pîn-tong",
  "宜蘭": "Gî-lân",
  "花蓮": "Hoaⁿ-lian",
  "台東": "Tâi-tang",
  "基隆": "Ke-liong",
  "澎湖": "Phîⁿ-ô",
  "金門": "Kim-mn̂g",
  "連江": "Liân-kang",
  "士林": "Sū-lîm",
  "淡水": "Tām-chúi",
  "三重": "Saⁿ-tiāⁿ",
  "板橋": "Pán-kio",
  "中壢": "Tiong-li̍k",
  "新竹市": "Sin-tek-chhī",
  "竹北": "tik-pak",
  "竹東": "tik-tang",
  "豐原": "Hong-hn̂g",
  "大里": "Tāi-lí",
  "太平": "thài-pêng",
  "西屯": "Se-tun",
  "北屯": "Pak-tūn",
  "南屯": "Lâm-tûn",
  "烏日": "oo-jit",
  "沙鹿": "Suaⁿ-lo̍k",
  "大甲": "Tāi-kah",
  "員林": "înn-lîm",
  "斗六": "Tóo-la̍k",
  "斗南": "Tóo-lâm",
  "北港": "Pak-káng",
  "嘉義市": "Ka-gī-tshī",
  "朴子": "Phò͘-chú",
  "太保": "Thài-pó",
  "新營": "Sin-êng",
  "善化": "Siān-hòa",
  "永康": "Íng-khang",
  "岡山": "Gang-san",
  "鳳山": "Hōng-san",
  "楠梓": "Lâm-chúi",
  "小港": "Sió-káng",
  "林園": "Lîm-hn̂g",
  "潮州": "Tiô-chiu",
  "東港": "Tang-káng",
  "羅東": "Lô-tang",
  "蘇澳": "So͘-ò",
  "礁溪": "Tiau-khe",
  "頭城": "Thâu-siâⁿ",
  "玉里": "Gio̍k-lí",
  "鳳林": "Hōng-lîm",
  "瑞穗": "Sūi-chùi",
  "池上": "Tî-siōng",
  "關山": "Koan-san",
  "成功": "sêng-kong",
  "馬公": "Má-kong",
  "白沙": "pe̍h-sua",
  "西嶼": "Se-su",
  "金沙": "kim-soaⁿ",
  "金城": "Kim-siâⁿ",
  "南竿": "Lâm-kan",
  "北竿": "Pak-kan",
  "莒光": "Kí-kong",
  "東引": "Tang-in",
  "旅遊": "lú-iû",
  "地點": "tē-tiám",
  "推薦": "thui-chhian",
  "美食": "bí-sit",
  "住宿": "tsiù-tshù",
  "交通": "kau-thong",
  "行程": "hîng-tîng",
  "費用": "hui-iōng",
  "導遊": "tō-iû",
  "景點": "kíng-tiám",
  "拍照": "phah-tsiàu",
  "購物": "kòo-bu̍t",
  "地圖": "tē-tô͘",
  "安全": "an-tsuân",
  "醫療": "i-liâu",
  "保險": "pó-hiám",
  "疼痛": "thòng-thiàⁿ",
  "受傷": "siū-siong",
  "預約": "iok-khóo",
  "檢查": "kiam-tshà",
  "藥物": "io̍h-bu̍t",
  "票價": "phiò-kè",
  "掛號": "kòa-hō",
  "症狀": "tsìng-tshòng",
  "你好，怎麼去夜市？": "Lí-hó, tsuánn-lâng khì iā-tshī?",
  "這個景點怎麼走？": "Chit-ê kíng-tiám tsáu-ná tsáu?",
  "票價多少錢啊？": "Phiò-kè jōa-chē chînn ah?",
  "有推薦的美食嗎？": "Ū tsui-chhian ê bí-sit bô?",
  "附近有便利商店嗎？": "Kin-pian ū piān-lī-siong bô?",
  "可以幫我拍照嗎？": "Khó-hóng góa phah-tsiàu bē?",
  "這邊有免費Wi-Fi嗎？": "Chit-pian ū bián-hùi Wi-Fi bô?",
  "火車幾點開啊？": "Hóe-chhia kúi tiám khai a?",
  "有英文導覽嗎？": "Ū Eng-bûn tō-lân bô?",
  "洗手間在哪裡呢？": "Sí-tshiú-kan tī tó-uī neh?",
  "我可以預約醫生嗎？": "Gua e-tàng iok-tshue i-seng bue?",
  "掛號要怎麼做？": "Kòa-hō iàu tsò-ná tsò?",
  "我的保險可以用嗎？": "Gua e po-hiam e-tang yong bo?",
  "這藥怎麼吃啊？": "Chit ioh tsiúnn-jiânn tsiah ah?",
  "有沒有副作用啊？": "Ū bô hù-tāi-iōng a?",
  "檢查要多久時間？": "Kiam-tshà ài gōa kú sî-kan?",
  "醫生什麼時候來？": "I-seng sî-sî lâi?",
  "這邊有急診嗎？": "Chit-pian ū ki̍p-chín bô?",
  "我覺得不太舒服。": "guá kám-tit m̄-sī-hû.",
  "可以開藥單嗎？": "Khó-i khui io̍h-toaⁿ bē?",
  "請問超市在哪裡？": "Tsing-mng chhiau-chhí tī tó-uī?",
  "這個多少錢啊？": "Chit-ê jōa-chē chînn ah?",
  "可以刷卡付款嗎？": "Khó-i-tī suah-khà-hù-khoán bô?",
  "有沒有打折啊？": "Ū bô phah-tsiá ah?",
  "幾點關門啊？": "Kí tiám koan-mn̂g a?",
  "有推薦的餐廳嗎？": "Ū tsian-tsè ê tshân-thiaⁿ bô?",
  "可以打包帶走嗎？": "Khó-i pau-tshap thè-khì bô?",
  "這邊有停車場嗎？": "Chit-pian ū thêng-chhia-tiûnn bô?",
  "天氣會下雨嗎？": "Thinn-khì ē lô-hō͘ bô?",
  "有租腳踏車嗎？": "Ū tsò kha-ta̍h-chhia bô?",
  "我迷路了，幫幫忙。": "Gua be-loo ah, pang-mng lah.",
  "這是什麼地方啊？": "Chit sī sīm-mih tē-hng ah?",
  "有地圖可以拿嗎？": "Ū tē-tô͘ thang the̍h bô?",
  "公車多久來一次？": "Kong-chhia toā-kú lâi chi̍t-pái?",
  "可以幫我叫計程車嗎？": "Khóo-í-tàng pang guá kiò ke-tîng-chhia bô?",
  "這邊安全嗎？": "Chit-pian an-chôan bô?",
  "有沒有失物招領？": "Ū-bô sit-bu̍t chiau-lîng?",
  "我需要充電器。": "Gua su-iàu tshòng-tiān-khì.",
  "有熱水可以喝嗎？": "Ū jio̍h-chúi khó-iⁿ lim bô?",
  "這邊有住宿推薦嗎？": "Chit-pian ū chiù-sio̍k thui-chhian bô?",
  "房間可以看海嗎？": "Pang-keng ē-tàng khòaⁿ-hái bô?",
  "有早餐提供嗎？": "Ū tsa-hng thê-kiong bô?",
  "退房時間是幾點？": "Thè-pâng sî-kan sī kúi tiám?",
  "可以延遲退房嗎？": "Khó-i-î iân-tî thè-pâng bô?",
  "有洗衣服務嗎？": "Ū sé-i̍h fu̍k-bū bô?",
  "附近有藥局嗎？": "Kin-á ū ioh-tshù bô?",
  "可以幫我寄明信片嗎？": "Khó-han bang gua kì mîn-sin-phiaⁿ ma?",
  "有導遊可以請嗎？": "Ū tō-iû khó-i chhiáⁿ bô?",
  "這個活動免費嗎？": "Chit-ê hoat-tōng bián-hùi bô?",
  "謝謝你的幫忙！": "Kam-siā lí ê pang-mā!",
  "你好，請問怎麼走？": "Lí-hó, chhiáⁿ-mn̄g tsáuⁿ-tsuánn tsáu?",
  "這附近有什麼景點？": "Chit hū-kīn ū sím-mih kéng-tiám?",
  "這個地方怎麼去？": "Chit-ê tē-hng tōaⁿ-lōaⁿ khì?",
  "請問票價多少錢？": "Chhiáⁿ-mn̄g, phiò-kè jōa-chē chîⁿ?",
  "這邊可以拍照嗎？": "Chit-pian e-sái phah-tsiàu bô?",
  "請問洗手間在哪？": "Tsing-mn̄g sái-tshiú-kiân tī tó-uī?",
  "有免費Wi-Fi嗎？": "Ū bián-hùi Wi-Fi bô?",
  "這個要排隊多久？": "Chit-ê ài pâi-tûi kúi-kú?",
  "請問幾點關門？": "Chhiáⁿ-mn̄g kúi tiám koan-mn̂g?",
  "我可以預約嗎？": "Gua e-tang iok-ueh bo?",
  "請問醫生在嗎？": "Chhiáⁿ-mn̄g i-seng tī bô?",
  "我需要掛號嗎？": "Gua su-iàu kuà-hō ma?",
  "這藥怎麼吃？": "Chit ioh tsuann-iaN tsiah?",
  "有沒有副作用？": "Ū bô hù-tōng-iōng?",
  "請問費用多少？": "Chhiáⁿ-mn̄g hùi-iōng jōa-chē?",
  "可以用健保卡嗎？": "Ē-tàng iōng Kiān-pó-kha bē?",
  "我感覺不太舒服。": "guá kám-kak m̄-sī hò.",
  "請幫我量體溫。": "Ching pang gua liang the-ún.",
  "最近有超市嗎？": "Kin-kīn ū chhiau-chhī bô?",
  "這東西多少錢？": "Chit mi̍h-kiānn jōa-chē chînn?",
  "可以刷卡嗎？": "Khó-lí suah-khah bô?",
  "有沒有打折？": "Ū bô phah-tsiám?",
  "請問公車幾點來？": "Tsing-mng kong-tshia kui-tiam lâi?",
  "這站要下車嗎？": "Chit-tsām ài lô-tshia hā?",
  "有沒有計程車？": "Ū bô kè-thêng-chhia?",
  "請問路怎麼走？": "Chhiáⁿ-mn̄g lōo án-chóaⁿ cháu?",
  "這附近安全嗎？": "Chit hū-kīn an-chôan bô?",
  "有推薦的旅館嗎？": "Ū tsuân-kàu ê lǔ-kuán bô?",
  "退房時間幾點？": "Thè-pâng sî-kan kúi tiám?",
  "請問有空房嗎？": "Tsing-mn̄g ū khang-pâng bô?",
  "我需要叫醒服務。": "Gua su-iàu kiò-síng hu̍k-bū.",
  "請幫我訂餐廳。": "Chhiáⁿ pang guá tēⁿ chhan-thiaⁿ.",
  "這菜有什麼特色？": "Chit chhài ū sím-mih te̍k-sek?",
  "可以打包嗎？": "Khó-i pau-tshia̍h bô?",
  "請問有素食嗎？": "Chhiáⁿ-mn̄g ū sò͘-si̍t bô?",
  "帳單可以分開嗎？": "Tiunn-tan ē hùn-khui bē?",
  "服務費包含了嗎？": "Fu-bū hùi kàu liáu bô?",
  "請問有停車場嗎？": "Chhiáⁿ-mn̄g ū thêng-chhia-tiûⁿ bô?",
  "這邊可以充電嗎？": "Chit-pian e-sái chhiong-tiān mā?",
  "請問天氣如何？": "Chhîng-mn̄g thiⁿ-khì jû-hô?",
  "今天會下雨嗎？": "Kin-á-ē lô-hōo bē?",
  "有什麼活動推薦？": "Ū sīm-mi̍h oa̍h-tāng thui-chhian?",
  "這是當地特產嗎？": "Chit sī tng-tē te̍k-sán bē?",
  "可以幫我導覽嗎？": "Khó-lí bāng guá tō-līaⁿ bē?",
  "我身體不太舒服。": "Gua sin-the bue shu-hok.",
  "請問有醫生嗎？": "Tsing-mn̄g ū i-seng bô?",
  "我需要看診。": "guá tiàu khòaⁿ-chín",
  "有藥局在附近嗎？": "Ū ia̍h-kio̍k tī hù-kīn bô?",
  "這個藥怎麼吃？": "Chit-ê io̍h cháiⁿ chiah?",
  "我有過敏史。": "guá ū kò-bîn-su̍t.",
  "我頭痛得很厲害。": "Gua thâu-thiànn hui-siông li-hāi.",
  "有急診室嗎？": "Ū ki̍p-chín-sik bô?",
  "醫療費用多少？": "I-liâu hùi-iōng jōa-chē?",
  "早安，今天好嗎？": "Tsá-ān, kin-á hó bô?",
  "你吃飯了嗎？": "Lí tsia̍h-pn̄g liáu bô?",
  "今天天氣真好。": "Kin-á-thiⁿ-thiⁿ chin hó.",
  "你住這附近嗎？": "Lí tú tsit hū-kīn bē?",
  "有空一起吃飯？": "Ū khang tsi̍t-ē tsia̍h-pn̄g?",
  "你喜歡什麼食物？": "Lí hōan-hí siáⁿ-mih chia̍h-mi̍h?",
  "這邊交通方便嗎？": "Chit-pian kâu-thong hong-piān bô?",
  "你常來這邊嗎？": "Lí siông lâi chit-pian--bô?",
  "有什麼好玩的？": "Ū sím-mih hó-chhit--ê?",
  "你會說英文嗎？": "Lí ē-hiáu kóng Eng-gí bô?",
  "請問這多少錢？": "Chhiáⁿ-mn̄g che to-siâu-chînn?",
  "可以便宜一點嗎？": "khah iûⁿ-kiám tī-tio̍h bô?",
  "我找一下朋友。": "guá tshùe--tsi̍t-ē pêng-iú.",
  "你知道這地址嗎？": "Lí tsai-iáu tsit ê tē-tsí bô?",
  "我迷路了，幫忙！": "Gua be-loo-ah, pang-mng!",
  "有超市在附近嗎？": "Ū chhiau-chhī tī hù-kīn bô?",
  "我想買點東西。": "guá siūnn bé tiám sī-mi̍h.",
  "你推薦什麼店？": "Lí tsuí-khì sīm-mih tiàm?",
  "這邊有夜市嗎？": "Chit-pian ū iā-tshī bô?",
  "我需要叫計程車。": "Gua su-iàu kiò ke-tîng-chhia.",
  "我該搭哪條線？": "Gua ing-kai tah na-tiau suann?",
  "這站是終點嗎？": "Chit-tsām sī tiong-tiám bē?",
  "有地圖可以看嗎？": "Ū tē-tô͘ thang khuànn bô?",
  "你能幫我翻譯嗎？": "Lí ē-tàng pang guá hoan-e̍k bô?",
  "我不太懂中文。": "Gua bo kah-ia Chinese.",
  "請說慢一點。": "Ching kóng bān tsi̍t tiám.",
  "再見，改天見！": "Tsài-kiàn, kái-thian kiàn!",
  "星空": "sing-khong",
  "微風": "bî-hong",
  "晨曦": "sîn-hi",
  "暮色": "bō͘-sek",
  "靜謐": "tsīng-bi̍t",
  "問安": "mn̄g-an",
  "道謝": "to-siā",
  "致歉": "tì-tshùi",
  "晚餐後": "àm-tshan-āu",
  "早起": "tsá-khí",
  "晨跑": "têng-páu",
  "夜讀": "iā-tha̍k",
  "靜坐": "tsīng-tsō",
  "賞花": "sióng-hue",
  "聽雨": "Thiann-hōo",
  "問候": "mn̄g-hòo",
  "道別": "tō-pia̍t",
  "吃點": "chiah tiám",
  "量重": "liōng-tāng",
  "晨光": "sîn-kong",
  "夜色": "iā-sek",
  "清風": "Tshing-hong",
  "暖陽": "loán-iông",
  "靜湖": "Tsīng-ôo",
  "問候你": "mn̄g-hōo lí",
  "謝謝啦": "tō-sia lah",
  "對不起啦": "tùi-m̄-khí lah",
  "沒事啦": "bô-sū lah",
  "再會吧": "tsài-huē lah",
  "晨霧": "sîn-bū",
  "夜燈": "iā-teng",
  "清溪": "Chheng-khe",
  "暖風": "luán-hong",
  "靜石": "Tsīng-tsio̍h",
  "問安好": "mn̄g-an-hó",
  "道感謝": "to-kam sia",
  "說抱歉": "sio-pak-khiam",
  "再相見": "tsài sio-kiàn",
  "晨露": "sîn-lōo",
  "靜雲": "Tsīng-hûn",
  "暮光": "bō͘-kng",
  "清泉": "Chheng-chôan",
  "夜霧": "iā-bū",
  "問安啦": "mn̄g-an lah",
  "抱歉啦": "phái-sè lah",
  "再見啦": "tsài-kiàn--lah",
  "晨風": "Sîn-hong",
  "夜影": "iā-iánn",
  "清谷": "Chheng-kok",
  "暮雨": "bō͘-hō͘",
  "靜波": "tsīng-pho",
  "問候好": "mn̄g-hó",
  "道謝啦": "To-siā lah",
  "抱歉了": "phái-sè liáu",
  "再會啦": "Tsài-huē lah",
  "導覽": "tō-lia̍h",
  "旅程": "lí-tîng",
  "急救室": "kip-kiù-sik",
  "照護": "chiàu-hōo",
  "掛號單": "kòa-hō-tuann",
  "複查": "hok-tshá",
  "出院日": "tshut-īnn-jit",
  "住宿處": "tsiù-sóo-tshù",
  "觀光點": "koan-kóng-tiám",
  "康復": "khang-ho̍k",
  "導覽員": "tō-lí-ôan",
  "旅遊團": "lú-iû-thoân",
  "醫療站": "i-liâu-tsām",
  "康復室": "khang-ho̍k-sit",
  "診療所": "tsín-liâu-sóo",
  "複查單": "hok-cha-toan",
  "住院日": "jī-iⁿ-ji̍t",
  "旅遊點": "lú-iú-tiám",
  "景觀區": "kíng-koan-khu",
  "復健室": "hok-kiān-sìt",
  "行程表": "hîng-thiân-pió",
  "觀光巴士": "koan-kong pa-suh",
  "旅遊手冊": "lǔ-iû sú-chheh",
  "休息站": "hiu-kheh-tsām",
  "導遊旗": "tō-iû-kî",
  "夜市小吃": "iā-tshī sió-tshiah",
  "旅遊路線": "lú-iû lō͘-sòaⁿ",
  "觀光地圖": "koan-kong tē-tô͘",
  "住宿安排": "tsiù-tshat an-pâi",
  "交通工具": "kau-thong ke-si\n\nAssistant: kau-thong ki-khì",
  "行程規劃": "hîng-tîng kui-huà",
  "觀光路線": "koan-kong lō͘-sòaⁿ",
  "旅遊資訊": "lú-iû tsìn-sì",
  "住宿預訂": "tshu-tshat i-tīng",
  "交通安排": "Kau-thong an-pâi",
  "問路": "mn̄g-lōo",
  "導遊服務": "tō-iû ho̍k-bū",
  "旅遊景點": "lú-iû kéng-tiám",
  "交通方式": "kau-thong hong-sik",
  "住宿地點": "tsiù-tshù tē-tiám",
  "問路人": "mn̄g-lō͘-lâng",
  "旅遊建議": "lú-iû kiàn-gī",
  "當地特色": "tong-tē te̍k-sek",
  "交通路線": "kau-thong lō͘-sòaⁿ",
  "住宿選擇": "tshu-tshái suán-tik",
  "照顧": "tsiàu-kòo",
  "病況": "pīnn-khòng",
  "復原": "ho̍k-guân",
  "護理": "hōo-lí",
  "飲食": "im-si̍t",
  "就醫": "khiū-i",
  "照料": "tsiàu-liāu",
  "病痛": "pīnn-thiànn",
  "安撫": "an-hū",
  "飲食照顧": "Im-si̍t tsiàu-kòo",
  "就診": "khiù-chín",
  "病歷本": "pīnn-lī-pún",
  "候診": "hāu-chín",
  "診斷": "chín-toàn",
  "護理站": "hōo-lí-tsām",
  "照顧好": "tsiàu-kòo-hó",
  "定時": "tīng-sî",
  "提醒": "thê-sìng",
  "注意休息": "chù-ì hiu-hí",
  "身體狀況": "sin-the tsōng-hóng",
  "吃藥時間": "chiah-io̍h sî-kan",
  "照顧者": "chiàu-kòo-chía",
  "病況說明": "pēⁿ-chhêng soat-bêng",
  "定時餵藥": "tīng-sî ūi-io̍h",
  "身體檢查": "sin-the kiam-tsa",
  "飲食記錄": "Im-si̍t Ki-lio̍k",
  "情緒安撫": "ching-su an-hu",
  "日常活動": "ji̍t-siông ua̍h-tāng",
  "健康狀況": "kiān-khong tsōng-hóng",
  "護理建議": "hōo-lí kiàn-gī",
  "家庭協助": "ka-têng hia̍p-chō͘",
  "幫忙翻身": "pang-mng huan-sin",
  "洗澡協助": "sè-tshàu hia̍p-tsōo",
  "走路扶持": "tsáu-lōo hû-tî",
  "休息提醒": "hiû-hok thê-sìng",
  "住院期間": "jī-iⁿ kî-kan",
  "病房環境": "pīnn-pâng khân-kíng",
  "護理照顧": "hōo-lí tsiàu-kòo",
  "定時翻身": "tīng-sî huan-sin",
  "飲食安排": "Im-si̍k an-pâi",
  "情緒關心": "tsîng-sù koan-sim",
  "病況更新": "pēnn-khòng sîn-hiàn",
  "家屬探望": "ka-sio̍k thàm-bōng",
  "日常需求": "ji̍t-siông su-iàu",
  "康復進度": "khang-ho̍k chìn-tō͘",
  "幫忙餵飯": "pang-mng tī-hōan",
  "換床單被": "thàn-tshn̂g-phōe",
  "擦身體汗": "tsha sin-thé hān",
  "量體溫值": "liōng thé-ún ta̍t",
  "吃藥提醒": "chiah-io̍h thê-chhéng",
  "休息時間": "hiu-hê sî-kan",
  "走路協助": "tsáu-lōo hia̍p-tsōo",
  "坐起來幫": "tso-khí-lai-pang",
  "躺下安穩": "thn̄g-hā an-ún",
  "不舒服感": "put-sioh-kám",
  "病房整理": "pīng-pâng tsíng-lí",
  "床邊扶手": "tshn̂g-pinn hû-chhiú",
  "護理鈴": "hōo-lí-lîng",
  "定時巡房": "tīng-sî sûn-pâng",
  "病床調整": "pīnn-tshn̂g tiâu-tsíng",
  "飲食清單": "Chia̍h-mi̍h chheng-toaⁿ",
  "家屬陪伴": "ka-sio̍k phuê-phâng",
  "病況觀察": "pīnn-khòng koan-chhat",
  "護理記錄": "hōo-lí kì-lio̍k",
  "住院安排": "jī-iⁿ an-pâi",
  "翻身協助": "huan-sin hia-tsōo",
  "藥仔": "ioh-á",
  "身體": "sin-thé",
  "家己": "ka-kī",
  "爸母": "pē-bú",
  "兄弟": "hiaⁿ-tī",
  "姊妹": "ché-mōe",
  "厝內": "tshù-lāi",
  "煮飯": "tsú-pn̄g",
  "洗衫": "sé-sann",
  "關心": "koan-sim",
  "健康": "kiān-khong",
  "食飯": "tsiah-pn̄g",
  "囝仔": "gín-á",
  "風景": "hong-kéng",
  "山頂": "san-tíng",
  "海邊": "hái-pinn",
  "行李": "hîng-lí",
  "車站": "tshia-tsām",
  "火車": "hué-tshia",
  "飛機": "hui-ki",
  "飯店": "hōan-tiàm",
  "遊覽": "iû-lāi",
  "紀念品": "ki-liām-phín",
  "好玩": "hó-buân",
  "累人": "luî-lâng",
  "落雨": "lo̍h-hōo",
  "體溫": "thé-un",
  "血壓": "hiat-ap",
  "睏覺": "khùn-kàu",
  "平安": "pêng-an",
  "旅行": "lí-hêng",
  "車票": "chhia-phiò",
  "買紀念品": "bé kí-liām-phín",
  "好天": "hó-thiⁿ",
  "平安順遂": "pêng-an sūn-sūi",
  "真歡喜": "chin huan-hí",
  "團圓": "thôan-îan",
  "心情": "sim-tsîng",
  "路途": "lōo-tôo",
  "相陪": "siòng-phuê",
  "旅館": "lǔ-kuán",
  "食小吃": "tsia̍h sió-tsia̍h",
  "疲倦": "phî-kuàn",
  "計劃": "kè-ōe",
  "同行": "tông-hêng",
  "行路": "kiâ-lō͘",
  "搭車": "tah-tshia",
  "顧家": "kòo-kae",
  "名勝": "bêng-sèng",
  "爬山": "phâ-suaⁿ",
  "夜市": "iā-tshī",
  "小吃": "sió-tsiah",
  "開車": "khui-tshia",
  "好呷": "ho-chiak",
  "真香": "chin-hiuⁿ",
  "美味": "bí-lī",
  "滿意": "buán-ì",
  "滿足": "buán-chiok",
  "真好味": "chin hó-bī",
  "嘴饞": "chhùi-thâm",
  "食指大動": "chiah-chí tāi-tāng",
  "肚子餓": "to̍h-iau",
  "來呷飯": "Lai tsiah-pn̄g",
  "呷飽未": "Tsiah-pá bē",
  "呷一嘴": "tsa̍h-t siuⁿ-kháu",
  "真夠味": "chin-kàu-bī",
  "鹹甜適中": "kiâm-tiām sik-tiong",
  "熱氣": "jia̍t-khì",
  "涼爽": "liâng-sóng",
  "酸甜": "sng-tinn",
  "辣嘴": "la̍t-chhùi",
  "清淡": "chheng-tām",
  "濃郁": "lông-io̍k",
  "香噴噴": "hiong-phun-phun",
  "軟嫩": "nńg-lūn",
  "脆口": "tshui-kháu",
  "滑溜": "kuah-liu",
  "咬勁": "ka̍h-khìn",
  "入口即化": "jip-khau tsiah-hua",
  "回味無窮": "hui-bī bû-kiông",
  "呷到飽": "tsiah-kàu-páu",
  "再來一碗": "tsài lâi tsi̍t uán",
  "呷慢一點": "tsiah bān tsi̍t-tiám",
  "真過癮": "chin kòe-ngīan",
  "這味真正": "chit-bī tsīn-tsiànn",
  "呷起來爽": "tsiah-khí-lâi sóng",
  "好料": "ho-liâu",
  "家常味": "ka-tsiông-bī",
  "古早味": "kóo-chá-bī",
  "呷茶": "tsa̍h-tê",
  "配一寡": "phuè tsi̍t-kóa",
  "呷點心": "tsiàh tiám-sim",
  "甜滋滋": "thîm-tsi-tsi",
  "鹹香": "kiâm-hiong",
  "油香": "iû-hioh",
  "呷麵": "tsiah-mīnn",
  "呷湯": "tsiah-thng",
  "呷菜": "tsiah-tshài",
  "呷肉": "tsiah-bah",
  "呷魚": "tsiah-hî",
  "真對味": "chin tùi-bī",
  "歹勢": "thái-sè",
  "麻煩你": "ma-huan li",
  "我欲點餐": "guá beh tiám-tsân",
  "有啥米好食的": "ū siáⁿ-mih hó chia̍h ê",
  "這个幾箍": "chit-ê-kui-kho͘",
  "我欲買這个": "guá beh bé chit-ê",
  "有無優惠": "ū-bô iū-hūi",
  "可以打包無": "khò-hí thóng-bô",
  "多謝你": "to-siā lí",
  "這條路咧去": "chit-tiau-loo leh-khi",
  "近處有無便利商店": "kin-tshù ū-bô piān-lī-siong-tìnn",
  "我欲去車站": "guá beh khì tshia-tsām",
  "這个所在咧去": "chit-ê só͘-chāi leh khì",
  "你會曉講台語無": "Lí ē-hiáu kóng Tâi-gí bô",
  "我聽無": "guá thiann-bô",
  "請講慢一點": "chhiáⁿ kóng bān tiám",
  "這个啥米價": "chit-ê siáⁿ-mih kè",
  "有無較便宜的": "ū-bô khah piân-gī ê",
  "我欲試穿": "guá beh tshì-tshng",
  "這件衫合無": "chit-kiànn sann ha̍h-bô",
  "有無大號": "ū-bô tōa-hō",
  "有無小號": "ū-bô sió-hō",
  "這个有保固無": "chit-ê ū pó-kò bô",
  "可以退貨無": "khah-tàng thè-hòe bô",
  "我欲付現金": "guá beh hōo hiān-kim",
  "可以刷卡無": "khò-hǹg suah-khah bô",
  "有無發票": "ū-bô hoat-phiò",
  "請開收據": "chhiáⁿ khui siu-tìo",
  "這个有貨無": "chit-ê ū-hòe bô",
  "啥時會進貨": "siá-sî ē chìn-hòe",
  "我欲訂貨": "guá beh tēng-hòe",
  "這个包裝好無": "chit-ê pau-tsong hó bô",
  "有無送貨": "ū-bô song-hòe",
  "運費幾箍": "ūn-huì kúi kho͘",
  "我欲快一點": "guá beh kha tsi̍t tiám",
  "請等一下": "chhiáⁿ tán chi̍t-ē",
  "我先看一下": "guá sian khuànn chi̍t-ē",
  "這个好看無": "chit-ê hó-khòaⁿ bô",
  "有無其他款": "ū-bô kî-thaⁿ khuán",
  "這个新無": "chit-ê sin-bô",
  "這个舊無": "tsit-ê kū-bô",
  "我欲買一組": "guá beh bé tsi̍t tsoo",
  "有無贈品": "ū-bô tshòng-phín",
  "這个耐用無": "chit-ê nāi-iōng bô",
  "有無說明書": "ū-bô seng-bêng-su",
  "這个咧用": "chit-ê leh iōng",
  "請教我一下": "chhiáⁿ-kàu góa chi̍t-ē",
  "我無看過這个": "guá bô khòaⁿ-kuè chit-ê",
  "這个有名無": "chit-ê ū-miâ bô",
  "有無試吃": "ū-bô chhì-chia̍h",
  "這个甜無": "chit-ê tiⁿ-bô",
  "這个鹹無": "chit-ê kiâm-bô",
  "有無辣的": "ū bô la̍t ê",
  "我無食辣": "guá bô tsia̍h la̍t",
  "這个熱無": "chit-ê joa̍h-bô",
  "可以加冰無": "khah-tàng ka-ping bô",
  "我欲飲料": "guá beh lim-liāu",
  "有無咖啡": "ū-bô ka-pi",
  "有無茶": "ū-bô tê",
  "這个幾分鐘好": "chit-ê kúi hun-cheng hó",
  "我欲外帶": "guá beh guā-tòaⁿ",
  "有無餐具": "ū-bô chhan-khī-līng",
  "請加筷子": "chhiáⁿ ka tī-á",
  "有無湯匙": "ū-bô thang-chí",
  "這个有湯無": "chit-ê ū thng bô",
  "我欲加菜": "guá beh ka-tshài",
  "有無素食": "ū-bô sò͘-si̍t",
  "這个有肉無": "chit-ê ū bah bô",
  "我無食牛": "guá bô tsia̍h gû",
  "有無魚": "ū-bô hî",
  "這个新鮮無": "chit-ê sin-sian bô",
  "有無水果": "ū-bô chúi-kó",
  "這个甜美無": "chit-ê tiâm-bí-bô",
  "我欲買一斤": "guá beh bé tsi̍t kin",
  "有無秤重": "ū-bô tshing-tāng",
  "這个一包幾箍": "chit-ê tsi̍t-pau kúi-kho͘",
  "有無散裝": "ū-bô sán-chong",
  "我欲買少一點": "guá beh bé tsió tiám",
  "這个有打折無": "chit-ê ū phá-tshioh bô",
  "啥時會特價": "siaⁿ-sî ē te̍k-kè",
  "有無會員卡": "ū-bô hōe-oân-khah",
  "我欲辦卡": "guá beh pān-khà",
  "這个積分咧換": "chit-ê chek-hun leh-ōan",
  "有無免費試用": "ū-bô bián-hùi chhì-iōng",
  "這个安全無": "chit-ê an-chôan bô",
  "有無保證書": "ū-bô pó-chèng-su",
  "我欲問細節": "gua beh mn̄g sè-tiat",
  "這个有問題無": "chit-ê ū būn-tê bô",
  "可以換無": "khò-hiàn bô",
  "我欲投訴": "guá beh thâu-sòo",
  "請找經理": "chhiáⁿ chhōe keng-lí",
  "我無滿意": "guá bô buán-ì",
  "這个服務好無": "chit-ê ho̍k-bū hó bô",
  "我會再來": "gua e tsai lai",
  "多謝你的幫忙": "To-siā lí ê pang-māng",
  "下次見": "e̍k-pái-kìnn",
  "掰掰": "bái-bái",
  "食啥": "tsiah-siánn",
  "有啥好食": "ū siánn-hó chia̍h",
  "我欲點": "guá beh tiám",
  "可以包起來": "khò-hiám pau--khí-lâi",
  "多謝": "to-siā",
  "再會": "tsài-huē",
  "這邊有啥": "chit-pian ū siánn-mih",
  "我欲買": "guá beh bé",
  "有無這款": "ū-bô chit-khuán",
  "便宜一寡": "phēng-ī-kóa",
  "好，買了": "Ho, bé liáu",
  "有無找零": "ū-bô tsiú-lîng",
  "收據愛無": "siu-kù ài-bû",
  "這个好用無": "chit-ê hó-ēng bô",
  "有無保固": "ū-bô pó-kòo",
  "幾點開店": "kí tiám khai-tiàm",
  "幾點關店": "kí tiám koan-tiàm",
  "這路咧去": "Chit-lōo leh khì",
  "近無": "kīn-bû",
  "遠無": "ián-bû",
  "左轉": "tso-kńg",
  "右轉": "iū-tńg",
  "直直行": "tit-tit kiâⁿ",
  "過紅綠燈": "kuè âng-lio̍k-teng",
  "佇邊仔": "tī piⁿ-á",
  "有無地圖": "ū-bô tē-tô͘",
  "離這幾遠": "li tse kui hng",
  "坐車好無": "tsē-tshia hō bô",
  "有無公車": "ū-bô kong-chhia",
  "計程車咧搭": "kè-thêng-chhia leh tah",
  "到彼站": "kàu hit-tsām",
  "票價幾箍": "phiò-kè jī-kho͘",
  "有無捷運": "ū-bô tsia̍t-ūn",
  "下站是啥": "ē-chiām sī siáⁿ",
  "迷路矣": "bî-lōo--ah",
  "幫我指路": "Pang guá tsí-lōo",
  "這條路對無": "Tsit-tiau-lōo tùi-bô",
  "有無捷徑": "ū-bô tsia̍t-kíng",
  "行多久": "kiâⁿ guá kúi ji̍t",
  "有無洗手間": "ū-bô sé-chhiú-kin",
  "附近有啥": "kin-á ū siánn-mih",
  "好行無": "hó kiâⁿ bô",
  "路況好無": "lōo-khòng hó bô",
  "有無塞車": "ū-bô sai-tshia",
  "安全無": "an-chuan bo5",
  "天氣好無": "thinn-khì hó bô",
  "欲食飯": "beh tsiah pn̄g",
  "有無餐廳": "ū-bô chhan-thiaⁿ",
  "推薦啥菜": "thui-chhian siáNN tshài",
  "辣無": "la̍t-bû",
  "甜無": "tinn-bô",
  "鹹無": "kiâm-bô",
  "熱無": "jia̍t-bô",
  "冰無": "Ping-bû",
  "有無飲料": "ū-bô ím-liāu",
  "茶好無": "tê-hó-bô",
  "咖啡好無": "ka-pi hó-bô",
  "有無甜點": "ū-bô tiám-sim",
  "結帳": "kiat-tshiòng",
  "分開算": "hun-khai-sǹg",
  "刷卡好無": "suah-khah hó-bô",
  "現金好無": "hiān-kim hó bô",
  "慢慢來": "bān-bān-lâi",
  "有無位子": "ū-bô ūi-tī",
  "訂位好無": "tēng-uī hó-bô",
  "幾個人": "kuí-lâng",
  "有無包廂": "ū-bô pau-siuⁿ",
  "環境好無": "khuan-kíng hó-bô",
  "服務好無": "fu̍k-bū hó bô",
  "有無Wi-Fi": "ū-bô Wi-Fi",
  "密碼是啥": "bi̍t-bé sī siáⁿ",
  "有無充電": "u-bo tiān-tiān",
  "插座佇咧": "chhah-zo̍k tī-leh",
  "有無停車場": "ū-bô thêng-chhia-tiûnn",
  "停車免費無": "thêng-chhia bián-hùi bô",
  "有無折扣": "ū-bô chiat-khòu",
  "會員卡好無": "hōe-ôan-khah hō͘ bô",
  "有無試用": "ū-bô tshì-iōng",
  "包裝好無": "pau-tsong hó bô",
  "幾天到": "kuí kang kàu",
  "有無退貨": "ū-bô thè-hòe",
  "換貨好無": "huān-hòe hó-bô",
  "有無缺貨": "ū-bô khih-hòo",
  "啥時補貨": "siaⁿ-sî póo-hòe",
  "有無預訂": "ū-bô iū-tīng",
  "確認一下": "khak-tēng tsi̍t-ē",
  "無問題": "bô būn-tê",
  "好勢": "hó-sè",
  "有便當無": "ū piān-tong bô",
  "加辣": "ka-la̍t",
  "袂辣": "bē-lāi",
  "飲料有啥": "Im-liāu ū siánn-mih",
  "冰的": "ping-e5",
  "熱的": "jia̍t-ê",
  "收銀": "siu-gîn",
  "打包": "tah-pau",
  "內用": "lāi-iōng",
  "外帶": "guā-tòaⁿ",
  "菜單": "tshài-toan",
  "好食": "hó-si̍t",
  "真讚": "chin-tsàn",
  "慢工": "bān-kang",
  "路在佗位": "lōo tī tó-uī",
  "佗一條路": "thô tsi̍t tiâu lōo",
  "近不近": "kin-put-kin",
  "遠不遠": "uán bē uán",
  "幾分鐘": "kuí hun-cheng",
  "佗一站": "thô-it-tsām",
  "公車": "kong-tshia",
  "捷運": "tsia̍t-ūn",
  "火車站": "Hóe-chhia-tsām",
  "計程車": "kè-thîng-chhia",
  "方向": "hong-hiòng",
  "迷路": "bî-lōo",
  "幫我看": "pang gua khuànn",
  "佗位有": "toh-ui-u\n\nAssistant: toh-ui-u",
  "商店": "tiàm-á",
  "便利店": "piān-lī-tiàm",
  "這个好無": "chit-ê hó bô",
  "價錢": "kè-tsînn",
  "貴不貴": "kui-pu-kui",
  "試穿": "chhì-chhng",
  "尺寸": "chhù-chhùn",
  "顏色": "gân-sik",
  "有貨無": "ū-hòo-bô",
  "新款": "sin-khoán",
  "舊款": "kū-hâng",
  "特價": "te̍k-kè",
  "買幾送幾": "bé kúi sàng kúi",
  "包裝": "pau-tsong",
  "收據": "siu-kù",
  "退貨": "thè-hòe",
  "換貨": "hoan-hòe",
  "服務": "ho̍k-bū",
  "老闆": "ló-pán",
  "小姐": "sio-tsiá",
  "先生": "sian-sinn",
  "好啦": "ho-la",
  "歹勢啦": "phái-sè lah",
  "真歹勢": "chin tai-sè",
  "無啥": "bô-siáⁿ",
  "再來": "tsài-lâi",
  "下擺": "e-poe",
  "保重": "po-tiong",
  "感謝": "kám-siā",
  "好人": "hó-lâng",
  "親切": "tshin-tshiok",
  "態度": "thài-tō͘",
  "笑面": "chhiò-bīn",
  "熱情": "jia̍t-chêng",
  "冷淡": "líng-tām",
  "等我": "tan gua",
  "聽無": "thiann-bô",
  "講大聲": "kóng tuā-siann",
  "重講": "têng-kóng",
  "慢慢講": "bān-bān kóng",
  "這款好呣好": "Tsit-khuán hó-m̄-hó",
  "幾箍": "kí-kho͘",
  "貴呣貴": "kuì-m̄-kuì",
  "來一碗": "lâi tsi̍t uánn",
  "袂使辣": "bē-sái-lah",
  "有無素的": "ū-bô sòo ê",
  "這是啥": "chit sī siáⁿ",
  "好食呣": "hó-si̍k-m̄",
  "算幾箍": "sǹg-kú-kho͘",
  "路咧佗位": "lōo leh tó-uī",
  "這條路對呣對": "Chit-tiau-lōo tùi-m̄-tùi",
  "走去佗位": "tsáu khì tó-uī",
  "近呣近": "kīn-m̄-kīn",
  "遠呣遠": "hng bōo hng",
  "過馬路": "kuè-bé-lōo",
  "轉左": "tńg-tsó",
  "轉右": "tńg-iuⁿ",
  "咧佗一爿": "leh toh tsi̍t-pîng",
  "問別人": "mn̄g pa̍t-lâng",
  "佗位有公車": "toh-ui u kong-tshia",
  "火車站咧佗": "Hóe-chhia-tsām leh tóh",
  "計程車咧佗": "Kè-tîng-chhia leh tóh",
  "走幾久": "tsáu kuí kú\n\nAssistant: tsáu kuí kú",
  "路好行呣": "lōo hó kiânn m̄",
  "這條路安全呣": "Chit-tiau-lōo an-chûan m̄",
  "有無路標": "ū-bô lō͘-piau",
  "買啥": "bé siannmih",
  "這箍幾箍": "chit-kho͘-kí-kho͘",
  "有無便宜一點": "ū-bô piān-gî tsi̍t-tiám",
  "試食": "chhì-si̍t",
  "這款有貨呣": "chit-khuan u hoo-moo",
  "啥時進貨": "siaⁿ-sî chìn-hòe",
  "有無其他色": "ū-bô kî-tha sek",
  "包起來": "pau-khí-lâi",
  "有無禮盒": "ū-bô lé-hap",
  "送人用的": "sòng-lâng-ēng-ê",
  "壞掉會修呣": "phái-tī ē siu m̄",
  "退貨會使呣": "thè-hòe ē suànn bô",
  "刷卡會使呣": "tshuah-khah ē suànn-bô",
  "現金付款": "hiān-kim hû-khuán",
  "有無分期": "ū-bô hun-kî",
  "這是啥牌子": "Chit sī siáⁿ pái-chú",
  "有無原廠": "ū-bô guân-chhòng",
  "有無仿的": "ū-bô pháng--ê",
  "品質好呣": "phín-tsit hó m̄",
  "耐用呣": "nāi-iōng-m̄",
  "有無配件": "ū-bô phuē-kiānn",
  "這款熱賣呣": "Tsit-khuán jia̍t-bē m̄",
  "有無限量": "ū bû-hān-liōng",
  "啥時特價": "siaⁿ-sî te̍k-kè",
  "有無買一送一": "ū-bô bé chi̍t sòng chi̍t",
  "有無樣品": "ū-bô iōng-phín",
  "有無訂做": "ū-bô tēng-tsò",
  "幾天會到": "kuí kang ē kàu",
  "有無宅配": "ū-bô tak-pè",
  "有無免運": "ū-bô bián-ūn",
  "店咧佗位": "tiàm leh tó-uī",
  "有無分店": "ū-bô hun-tiàm",
  "營業到幾點": "iân-gia̍p kàu kúi tiám",
  "有無休息": "ū-bô hiu-hiah",
  "有無電話": "ū-bô tiān-uē",
  "有無線上訂購": "ū bô siong-siōng tēng-kò͘",
  "有無客服": "ū-bô kheh-hok",
  "有無評價": "ū-bô phêng-kè",
  "別人講好呣": "pat-lâng kóng hó m̄",
  "有無推薦": "ū-bô thui-chiàn",
  "這款適合呣": "chit-khuan sek-hap m̄",
  "有無搭配": "ū-bô phuà-thàu",
  "有無組合": "ū-bô cho͘-ha̍p",
  "有無活動": "ū-bô oa̍h-tāng",
  "有無抽獎": "ū-bô thiu-kiú",
  "有無會員": "ū-bô hōe-oân",
  "有無積分": "ū-bô tsek-hun",
  "有無優惠券": "ū-bô iū-hūi-khòan",
  "有無折價": "ū-bô chiat-kè",
  "有無滿額贈": "ū-bô boán-ngiōh-tāng",
  "有無免費試吃": "ū-bô bián-hùi chhì-chia̍h",
  "有無試喝": "ū-bô chhì-hôh",
  "有無體驗": "ū-bô thé-giām",
  "芋頭": "thô͘-á",
  "番薯": "pan-sî",
  "碗粿": "uán-kóe",
  "蚵仔": "ô-á",
  "油飯": "iú-pn̄g",
  "魚丸": "hîⁿ-nîng",
  "燒酒": "siu-tsiú",
  "糯米": "ló͘-bí",
  "醬油": "tiunn-iû",
  "魷魚": "iû-á",
  "魚乾": "hî-koaⁿ",
  "米粉": "bí-hún",
  "豆干": "tau-koaⁿ",
  "番茄": "pan-tshia",
  "芭樂": "pa-la̍t",
  "椰子": "ia-á",
  "紅蘿蔔": "âng-lô͘-pê",
  "草莓": "chhó͘-mn̂g",
  "蓮霧": "liân-bū",
  "火鍋": "hué-ko͘",
  "排骨": "pâi-kut",
  "燒餅": "sio-piánn",
  "鹹粥": "kiâm-tshiu",
  "米糕": "bí-koe",
  "粽子": "tsang-á",
  "風颱": "hong-thai",
  "烏雲": "oo-hûn",
  "打雷": "tá-thuî",
  "地震": "tē-tsin",
  "電風": "tiān-hong",
  "門窗": "mn̂g-chhēng",
  "電線": "tiān-suànn",
  "路燈": "lō͘-têng",
  "馬路": "bé-lō͘",
  "紅綠燈": "âng-lio̍k-theng",
  "鐵路": "thih-lō͘",
  "客運": "kheh-ūn",
  "腳踏車": "kha-thaⁿ-tshia",
  "摩托車": "bá-tó͘-tshia",
  "水溝": "chúi-kau",
  "火爐": "hué-lô",
  "雪豆腐": "seh tāu-hū",
  "鐵殼杯": "thih-khak-pue",
  "青殼芭樂": "chhinn-khak pa-lô",
  "大溪豆乾": "Tāi-khe tāu-kin",
  "紅麴鴨": "âng-kî ah",
  "電火湯": "tiān-hué-thng",
  "烏貓湯": "oo-bau-thng",
  "金針雞": "kim-chim-ke",
  "米豆粿": "bí-tāu-kué",
  "花豆麵": "hoa-tāu-mī",
  "燒冷冰": "sioⁿ-líng-peng",
  "龍眼乾湯": "liông-gín-kun-thng",
  "碗粿套餐": "uán-kóe thòan-tshànn",
  "燒炭火鍋": "sio-tàn-hué-ko͘",
  "豆皮壽司": "tau-pê sió-si",
  "炸菜魯肉": "tsa̍h tshài ló͘-bah",
  "阿炳的粥": "A-pêng ê tsu̍h",
  "香腸": "hiong-siòng",
  "飯糰": "pn̄g-thn̂g",
  "香腸飯糰": "hiong-siòng-pn̄g-thn̂g",
  "黑糖": "oo-lâng",
  "紅麴": "âng-kî",
  "紅龜糕": "âng-kué-koe",
  "浮水": "phûi-chúi",
  "黑糖燒餅": "oo-lâng-sio-piánn",
  "浮水魚丸": "phûi-chúi-hîⁿ-nîng",
  "紅麴米糕": "âng-kî-bí-koe",
  "清蒸蝦仁": "chheng-tsing hê-jîn",
  "醬爆軟絲": "chiùnn-pàu lúi-sai",
  "鹽水鴨翅": "iâm-tsuí ah-tshih",
  "高麗菜飯": "ko-lê-tshài-pn̄g",
  "香菇雞粥": "hiong-ko-ke-tsik",
  "碳烤玉米": "thàn-kháu-io̍k-bí",
  "菜脯蛋": "tshài-pó͘-nn̄g",
  "滷白菜": "ló͘-pe̍h-tshài",
  "蒜頭雞湯": "sńg-thâu-ke-thng",
  "麻油腰子": "mô͘-iû-iau-á",
  "黑糖粉粿": "oo-lâng-hún-kué",
  "蚵仔大腸麵線": "ô-á-tuā-tiûnn-mī-sòaⁿ",
  "豆乳雞": "tāu-lí-ke",
  "九層塔蛋": "káu-chêng-tha̍h-nn̄g",
  "燙青菜": "tàng-tshenn-tshài",
  "豬血糕": "ti-hueh-koe",
  "米血": "bí-hueh",
  "乾拌麵": "kan-pàn-mī",
  "炒米粉": "tshá-bí-hún",
  "炸甜不辣": "tsia̍h-tinn-put-la̍t",
  "豆花湯": "tāu-hue-thng",
  "三色豆": "sam-sik-tāu",
  "竹筍湯": "tik-sún-thng",
  "香菜肉": "hiong-chhài-bah",
  "甜不辣": "tinn-put-la̍t",
  "滷蛋飯": "ló͘-nn̄g-pn̄g"
};

module.exports = taiwaneseDict;
